COUNTRIES = {
    "EU": {"name": "Union Européenne", "flag": "🇪🇺"},
    "FR": {"name": "France", "flag": "🇫🇷"},
    "US": {"name": "États-Unis", "flag": "🇺🇸"},
    "GB": {"name": "Royaume-Uni", "flag": "🇬🇧"},
    "CH": {"name": "Suisse", "flag": "🇨🇭"},
    "CA": {"name": "Canada", "flag": "🇨🇦"},
    "AU": {"name": "Australie", "flag": "🇦🇺"},
    "JP": {"name": "Japon", "flag": "🇯🇵"},
    "CN": {"name": "Chine", "flag": "🇨🇳"},
    "IN": {"name": "Inde", "flag": "🇮🇳"},
    "BR": {"name": "Brésil", "flag": "🇧🇷"},
    "MX": {"name": "Mexique", "flag": "🇲🇽"},
    "AR": {"name": "Argentine", "flag": "🇦🇷"},
    "CO": {"name": "Colombie", "flag": "🇨🇴"},
    "CL": {"name": "Chili", "flag": "🇨🇱"},
    "PE": {"name": "Pérou", "flag": "🇵🇪"},
    "MA": {"name": "Maroc", "flag": "🇲🇦"},
    "TN": {"name": "Tunisie", "flag": "🇹🇳"},
    "DZ": {"name": "Algérie", "flag": "🇩🇿"},
    "EG": {"name": "Égypte", "flag": "🇪🇬"},
    "SA": {"name": "Arabie Saoudite", "flag": "🇸🇦"},
    "AE": {"name": "Émirats Arabes Unis", "flag": "🇦🇪"},
    "QA": {"name": "Qatar", "flag": "🇶🇦"},
    "KW": {"name": "Koweït", "flag": "🇰🇼"},
    "BH": {"name": "Bahreïn", "flag": "🇧🇭"},
    "OM": {"name": "Oman", "flag": "🇴🇲"},
    "JO": {"name": "Jordanie", "flag": "🇯🇴"},
    "LB": {"name": "Liban", "flag": "🇱🇧"},
    "IL": {"name": "Israël", "flag": "🇮🇱"},
    "TR": {"name": "Turquie", "flag": "🇹🇷"},
    "RU": {"name": "Russie", "flag": "🇷🇺"},
    "UA": {"name": "Ukraine", "flag": "🇺🇦"},
    "PL": {"name": "Pologne", "flag": "🇵🇱"},
    "CZ": {"name": "République Tchèque", "flag": "🇨🇿"},
    "HU": {"name": "Hongrie", "flag": "🇭🇺"},
    "RO": {"name": "Roumanie", "flag": "🇷🇴"},
    "BG": {"name": "Bulgarie", "flag": "🇧🇬"},
    "HR": {"name": "Croatie", "flag": "🇭🇷"},
    "RS": {"name": "Serbie", "flag": "🇷🇸"},
    "SE": {"name": "Suède", "flag": "🇸🇪"},
    "NO": {"name": "Norvège", "flag": "🇳🇴"},
    "DK": {"name": "Danemark", "flag": "🇩🇰"},
    "IS": {"name": "Islande", "flag": "🇮🇸"},
    "ZA": {"name": "Afrique du Sud", "flag": "🇿🇦"},
    "NG": {"name": "Nigéria", "flag": "🇳🇬"},
    "KE": {"name": "Kenya", "flag": "🇰🇪"},
    "GH": {"name": "Ghana", "flag": "🇬🇭"},
    "SN": {"name": "Sénégal", "flag": "🇸🇳"},
    "CM": {"name": "Cameroun", "flag": "🇨🇲"},
    "CI": {"name": "Côte d'Ivoire", "flag": "🇨🇮"},
    "MU": {"name": "Maurice", "flag": "🇲🇺"},
    "TZ": {"name": "Tanzanie", "flag": "🇹🇿"},
    "UG": {"name": "Ouganda", "flag": "🇺🇬"},
    "RW": {"name": "Rwanda", "flag": "🇷🇼"},
    "ET": {"name": "Éthiopie", "flag": "🇪🇹"},
    "TH": {"name": "Thaïlande", "flag": "🇹🇭"},
    "VN": {"name": "Vietnam", "flag": "🇻🇳"},
    "ID": {"name": "Indonésie", "flag": "🇮🇩"},
    "MY": {"name": "Malaisie", "flag": "🇲🇾"},
    "SG": {"name": "Singapour", "flag": "🇸🇬"},
    "PH": {"name": "Philippines", "flag": "🇵🇭"},
    "KR": {"name": "Corée du Sud", "flag": "🇰🇷"},
    "TW": {"name": "Taïwan", "flag": "🇹🇼"},
    "HK": {"name": "Hong Kong", "flag": "🇭🇰"},
    "NZ": {"name": "Nouvelle-Zélande", "flag": "🇳🇿"},
    "PK": {"name": "Pakistan", "flag": "🇵🇰"},
    "BD": {"name": "Bangladesh", "flag": "🇧🇩"},
    "LK": {"name": "Sri Lanka", "flag": "🇱🇰"},
    "NP": {"name": "Népal", "flag": "🇳🇵"},
    "MM": {"name": "Myanmar", "flag": "🇲🇲"},
    "KH": {"name": "Cambodge", "flag": "🇰🇭"},
    "LA": {"name": "Laos", "flag": "🇱🇦"},
    "BE": {"name": "Belgique", "flag": "🇧🇪"},
    "NL": {"name": "Pays-Bas", "flag": "🇳🇱"},
    "DE": {"name": "Allemagne", "flag": "🇩🇪"},
    "IT": {"name": "Italie", "flag": "🇮🇹"},
    "ES": {"name": "Espagne", "flag": "🇪🇸"},
    "PT": {"name": "Portugal", "flag": "🇵🇹"},
    "AT": {"name": "Autriche", "flag": "🇦🇹"},
    "IE": {"name": "Irlande", "flag": "🇮🇪"},
    "FI": {"name": "Finlande", "flag": "🇫🇮"},
    "GR": {"name": "Grèce", "flag": "🇬🇷"},
    "LU": {"name": "Luxembourg", "flag": "🇱🇺"},
    "SK": {"name": "Slovaquie", "flag": "🇸🇰"},
    "SI": {"name": "Slovénie", "flag": "🇸🇮"},
    "EE": {"name": "Estonie", "flag": "🇪🇪"},
    "LV": {"name": "Lettonie", "flag": "🇱🇻"},
    "LT": {"name": "Lituanie", "flag": "🇱🇹"},
    "CY": {"name": "Chypre", "flag": "🇨🇾"},
    "MT": {"name": "Malte", "flag": "🇲🇹"},
    "MC": {"name": "Monaco", "flag": "🇲🇨"},
    "AD": {"name": "Andorre", "flag": "🇦🇩"},
    "SM": {"name": "Saint-Marin", "flag": "🇸🇲"},
    "VA": {"name": "Vatican", "flag": "🇻🇦"},
    "LI": {"name": "Liechtenstein", "flag": "🇱🇮"},
    "AL": {"name": "Albanie", "flag": "🇦🇱"},
    "MK": {"name": "Macédoine du Nord", "flag": "🇲🇰"},
    "ME": {"name": "Monténégro", "flag": "🇲🇪"},
    "BA": {"name": "Bosnie-Herzégovine", "flag": "🇧🇦"},
    "XK": {"name": "Kosovo", "flag": "🇽🇰"},
    "MD": {"name": "Moldavie", "flag": "🇲🇩"},
    "BY": {"name": "Biélorussie", "flag": "🇧🇾"},
    "GE": {"name": "Géorgie", "flag": "🇬🇪"},
    "AM": {"name": "Arménie", "flag": "🇦🇲"},
    "AZ": {"name": "Azerbaïdjan", "flag": "🇦🇿"},
    "KZ": {"name": "Kazakhstan", "flag": "🇰🇿"},
    "UZ": {"name": "Ouzbékistan", "flag": "🇺🇿"},
    "TM": {"name": "Turkménistan", "flag": "🇹🇲"},
    "KG": {"name": "Kirghizistan", "flag": "🇰🇬"},
    "TJ": {"name": "Tadjikistan", "flag": "🇹🇯"},
    "AF": {"name": "Afghanistan", "flag": "🇦🇫"},
    "IQ": {"name": "Irak", "flag": "🇮🇶"},
    "IR": {"name": "Iran", "flag": "🇮🇷"},
    "SY": {"name": "Syrie", "flag": "🇸🇾"},
    "YE": {"name": "Yémen", "flag": "🇾🇪"},
    "MN": {"name": "Mongolie", "flag": "🇲🇳"},
    "MV": {"name": "Maldives", "flag": "🇲🇻"},
    "BT": {"name": "Bhoutan", "flag": "🇧🇹"},
    "BN": {"name": "Brunei", "flag": "🇧🇳"},
    "TL": {"name": "Timor oriental", "flag": "🇹🇱"},
    "FJ": {"name": "Fidji", "flag": "🇫🇯"},
    "PG": {"name": "Papouasie-Nouvelle-Guinée", "flag": "🇵🇬"},
    "WS": {"name": "Samoa", "flag": "🇼🇸"},
    "TO": {"name": "Tonga", "flag": "🇹🇴"},
    "VU": {"name": "Vanuatu", "flag": "🇻🇺"},
    "NC": {"name": "Nouvelle-Calédonie", "flag": "🇳🇨"},
    "PF": {"name": "Polynésie française", "flag": "🇵🇫"},
    "PR": {"name": "Porto Rico", "flag": "🇵🇷"},
    "JM": {"name": "Jamaïque", "flag": "🇯🇲"},
    "HT": {"name": "Haïti", "flag": "🇭🇹"},
    "DO": {"name": "République dominicaine", "flag": "🇩🇴"},
    "CU": {"name": "Cuba", "flag": "🇨🇺"},
    "TT": {"name": "Trinité-et-Tobago", "flag": "🇹🇹"},
    "BB": {"name": "Barbade", "flag": "🇧🇧"},
    "BS": {"name": "Bahamas", "flag": "🇧🇸"},
    "PA": {"name": "Panama", "flag": "🇵🇦"},
    "CR": {"name": "Costa Rica", "flag": "🇨🇷"},
    "GT": {"name": "Guatemala", "flag": "🇬🇹"},
    "HN": {"name": "Honduras", "flag": "🇭🇳"},
    "SV": {"name": "Salvador", "flag": "🇸🇻"},
    "NI": {"name": "Nicaragua", "flag": "🇳🇮"},
    "BZ": {"name": "Belize", "flag": "🇧🇿"},
    "EC": {"name": "Équateur", "flag": "🇪🇨"},
    "BO": {"name": "Bolivie", "flag": "🇧🇴"},
    "VE": {"name": "Venezuela", "flag": "🇻🇪"},
    "PY": {"name": "Paraguay", "flag": "🇵🇾"},
    "UY": {"name": "Uruguay", "flag": "🇺🇾"},
    "GY": {"name": "Guyana", "flag": "🇬🇾"},
    "SR": {"name": "Suriname", "flag": "🇸🇷"},
    "GF": {"name": "Guyane française", "flag": "🇬🇫"},
    "LY": {"name": "Libye", "flag": "🇱🇾"},
    "SD": {"name": "Soudan", "flag": "🇸🇩"},
    "SS": {"name": "Soudan du Sud", "flag": "🇸🇸"},
    "TD": {"name": "Tchad", "flag": "🇹🇩"},
    "NE": {"name": "Niger", "flag": "🇳🇪"},
    "ML": {"name": "Mali", "flag": "🇲🇱"},
    "BF": {"name": "Burkina Faso", "flag": "🇧🇫"},
    "BJ": {"name": "Bénin", "flag": "🇧🇯"},
    "TG": {"name": "Togo", "flag": "🇹🇬"},
    "MR": {"name": "Mauritanie", "flag": "🇲🇷"},
    "GM": {"name": "Gambie", "flag": "🇬🇲"},
    "GN": {"name": "Guinée", "flag": "🇬🇳"},
    "GW": {"name": "Guinée-Bissau", "flag": "🇬🇼"},
    "SL": {"name": "Sierra Leone", "flag": "🇸🇱"},
    "LR": {"name": "Liberia", "flag": "🇱🇷"},
    "CV": {"name": "Cap-Vert", "flag": "🇨🇻"},
    "CF": {"name": "Centrafrique", "flag": "🇨🇫"},
    "CD": {"name": "RD Congo", "flag": "🇨🇩"},
    "CG": {"name": "Congo", "flag": "🇨🇬"},
    "GQ": {"name": "Guinée équatoriale", "flag": "🇬🇶"},
    "GA": {"name": "Gabon", "flag": "🇬🇦"},
    "AO": {"name": "Angola", "flag": "🇦🇴"},
    "MZ": {"name": "Mozambique", "flag": "🇲🇿"},
    "ZW": {"name": "Zimbabwe", "flag": "🇿🇼"},
    "ZM": {"name": "Zambie", "flag": "🇿🇲"},
    "MW": {"name": "Malawi", "flag": "🇲🇼"},
    "BW": {"name": "Botswana", "flag": "🇧🇼"},
    "NA": {"name": "Namibie", "flag": "🇳🇦"},
    "SZ": {"name": "Eswatini", "flag": "🇸🇿"},
    "LS": {"name": "Lesotho", "flag": "🇱🇸"},
    "MG": {"name": "Madagascar", "flag": "🇲🇬"},
    "KM": {"name": "Comores", "flag": "🇰🇲"},
    "SC": {"name": "Seychelles", "flag": "🇸🇨"},
    "DJ": {"name": "Djibouti", "flag": "🇩🇯"},
    "ER": {"name": "Érythrée", "flag": "🇪🇷"},
    "SO": {"name": "Somalie", "flag": "🇸🇴"},
    "BI": {"name": "Burundi", "flag": "🇧🇮"},
    "RE": {"name": "La Réunion", "flag": "🇷🇪"},
    "YT": {"name": "Mayotte", "flag": "🇾🇹"},
    "GP": {"name": "Guadeloupe", "flag": "🇬🇵"},
    "MQ": {"name": "Martinique", "flag": "🇲🇶"},
}

CURRENCIES = [
    {"code": "EUR", "name": "Euro", "symbol": "€", "country": "EU", "flag": "🇪🇺"},
    {"code": "USD", "name": "Dollar américain", "symbol": "$", "country": "US", "flag": "🇺🇸"},
    {"code": "GBP", "name": "Livre sterling", "symbol": "£", "country": "GB", "flag": "🇬🇧"},
    {"code": "CHF", "name": "Franc suisse", "symbol": "CHF", "country": "CH", "flag": "🇨🇭"},
    {"code": "CAD", "name": "Dollar canadien", "symbol": "C$", "country": "CA", "flag": "🇨🇦"},
    {"code": "AUD", "name": "Dollar australien", "symbol": "A$", "country": "AU", "flag": "🇦🇺"},
    {"code": "JPY", "name": "Yen japonais", "symbol": "¥", "country": "JP", "flag": "🇯🇵"},
    {"code": "CNY", "name": "Yuan chinois", "symbol": "¥", "country": "CN", "flag": "🇨🇳"},
    {"code": "INR", "name": "Roupie indienne", "symbol": "₹", "country": "IN", "flag": "🇮🇳"},
    {"code": "BRL", "name": "Real brésilien", "symbol": "R$", "country": "BR", "flag": "🇧🇷"},
    {"code": "MXN", "name": "Peso mexicain", "symbol": "$", "country": "MX", "flag": "🇲🇽"},
    {"code": "ARS", "name": "Peso argentin", "symbol": "$", "country": "AR", "flag": "🇦🇷"},
    {"code": "COP", "name": "Peso colombien", "symbol": "$", "country": "CO", "flag": "🇨🇴"},
    {"code": "CLP", "name": "Peso chilien", "symbol": "$", "country": "CL", "flag": "🇨🇱"},
    {"code": "PEN", "name": "Sol péruvien", "symbol": "S/", "country": "PE", "flag": "🇵🇪"},
    {"code": "MAD", "name": "Dirham marocain", "symbol": "DH", "country": "MA", "flag": "🇲🇦"},
    {"code": "TND", "name": "Dinar tunisien", "symbol": "DT", "country": "TN", "flag": "🇹🇳"},
    {"code": "DZD", "name": "Dinar algérien", "symbol": "DA", "country": "DZ", "flag": "🇩🇿"},
    {"code": "EGP", "name": "Livre égyptienne", "symbol": "E£", "country": "EG", "flag": "🇪🇬"},
    {"code": "SAR", "name": "Riyal saoudien", "symbol": "SR", "country": "SA", "flag": "🇸🇦"},
    {"code": "AED", "name": "Dirham des EAU", "symbol": "AED", "country": "AE", "flag": "🇦🇪"},
    {"code": "QAR", "name": "Riyal qatari", "symbol": "QR", "country": "QA", "flag": "🇶🇦"},
    {"code": "KWD", "name": "Dinar koweïtien", "symbol": "KD", "country": "KW", "flag": "🇰🇼"},
    {"code": "BHD", "name": "Dinar bahreïni", "symbol": "BD", "country": "BH", "flag": "🇧🇭"},
    {"code": "OMR", "name": "Rial omanais", "symbol": "OMR", "country": "OM", "flag": "🇴🇲"},
    {"code": "JOD", "name": "Dinar jordanien", "symbol": "JD", "country": "JO", "flag": "🇯🇴"},
    {"code": "LBP", "name": "Livre libanaise", "symbol": "L£", "country": "LB", "flag": "🇱🇧"},
    {"code": "ILS", "name": "Shekel israélien", "symbol": "₪", "country": "IL", "flag": "🇮🇱"},
    {"code": "TRY", "name": "Livre turque", "symbol": "₺", "country": "TR", "flag": "🇹🇷"},
    {"code": "RUB", "name": "Rouble russe", "symbol": "₽", "country": "RU", "flag": "🇷🇺"},
    {"code": "UAH", "name": "Hryvnia ukrainienne", "symbol": "₴", "country": "UA", "flag": "🇺🇦"},
    {"code": "PLN", "name": "Zloty polonais", "symbol": "zł", "country": "PL", "flag": "🇵🇱"},
    {"code": "CZK", "name": "Couronne tchèque", "symbol": "Kč", "country": "CZ", "flag": "🇨🇿"},
    {"code": "HUF", "name": "Forint hongrois", "symbol": "Ft", "country": "HU", "flag": "🇭🇺"},
    {"code": "RON", "name": "Leu roumain", "symbol": "lei", "country": "RO", "flag": "🇷🇴"},
    {"code": "BGN", "name": "Lev bulgare", "symbol": "лв", "country": "BG", "flag": "🇧🇬"},
    {"code": "HRK", "name": "Kuna croate", "symbol": "kn", "country": "HR", "flag": "🇭🇷"},
    {"code": "RSD", "name": "Dinar serbe", "symbol": "din", "country": "RS", "flag": "🇷🇸"},
    {"code": "SEK", "name": "Couronne suédoise", "symbol": "kr", "country": "SE", "flag": "🇸🇪"},
    {"code": "NOK", "name": "Couronne norvégienne", "symbol": "kr", "country": "NO", "flag": "🇳🇴"},
    {"code": "DKK", "name": "Couronne danoise", "symbol": "kr", "country": "DK", "flag": "🇩🇰"},
    {"code": "ISK", "name": "Couronne islandaise", "symbol": "kr", "country": "IS", "flag": "🇮🇸"},
    {"code": "ZAR", "name": "Rand sud-africain", "symbol": "R", "country": "ZA", "flag": "🇿🇦"},
    {"code": "NGN", "name": "Naira nigérian", "symbol": "₦", "country": "NG", "flag": "🇳🇬"},
    {"code": "KES", "name": "Shilling kényan", "symbol": "KSh", "country": "KE", "flag": "🇰🇪"},
    {"code": "GHS", "name": "Cedi ghanéen", "symbol": "₵", "country": "GH", "flag": "🇬🇭"},
    {"code": "XOF", "name": "Franc CFA (UEMOA)", "symbol": "CFA", "country": "SN", "flag": "🇸🇳"},
    {"code": "XAF", "name": "Franc CFA (CEMAC)", "symbol": "FCFA", "country": "CM", "flag": "🇨🇲"},
    {"code": "MUR", "name": "Roupie mauricienne", "symbol": "Rs", "country": "MU", "flag": "🇲🇺"},
    {"code": "TZS", "name": "Shilling tanzanien", "symbol": "TSh", "country": "TZ", "flag": "🇹🇿"},
    {"code": "UGX", "name": "Shilling ougandais", "symbol": "USh", "country": "UG", "flag": "🇺🇬"},
    {"code": "RWF", "name": "Franc rwandais", "symbol": "FRw", "country": "RW", "flag": "🇷🇼"},
    {"code": "ETB", "name": "Birr éthiopien", "symbol": "Br", "country": "ET", "flag": "🇪🇹"},
    {"code": "THB", "name": "Baht thaïlandais", "symbol": "฿", "country": "TH", "flag": "🇹🇭"},
    {"code": "VND", "name": "Dong vietnamien", "symbol": "₫", "country": "VN", "flag": "🇻🇳"},
    {"code": "IDR", "name": "Roupie indonésienne", "symbol": "Rp", "country": "ID", "flag": "🇮🇩"},
    {"code": "MYR", "name": "Ringgit malaisien", "symbol": "RM", "country": "MY", "flag": "🇲🇾"},
    {"code": "SGD", "name": "Dollar singapourien", "symbol": "S$", "country": "SG", "flag": "🇸🇬"},
    {"code": "PHP", "name": "Peso philippin", "symbol": "₱", "country": "PH", "flag": "🇵🇭"},
    {"code": "KRW", "name": "Won sud-coréen", "symbol": "₩", "country": "KR", "flag": "🇰🇷"},
    {"code": "TWD", "name": "Dollar taïwanais", "symbol": "NT$", "country": "TW", "flag": "🇹🇼"},
    {"code": "HKD", "name": "Dollar de Hong Kong", "symbol": "HK$", "country": "HK", "flag": "🇭🇰"},
    {"code": "NZD", "name": "Dollar néo-zélandais", "symbol": "NZ$", "country": "NZ", "flag": "🇳🇿"},
    {"code": "PKR", "name": "Roupie pakistanaise", "symbol": "Rs", "country": "PK", "flag": "🇵🇰"},
    {"code": "BDT", "name": "Taka bangladais", "symbol": "৳", "country": "BD", "flag": "🇧🇩"},
    {"code": "LKR", "name": "Roupie srilankaise", "symbol": "Rs", "country": "LK", "flag": "🇱🇰"},
    {"code": "NPR", "name": "Roupie népalaise", "symbol": "Rs", "country": "NP", "flag": "🇳🇵"},
    {"code": "MMK", "name": "Kyat birman", "symbol": "K", "country": "MM", "flag": "🇲🇲"},
    {"code": "KHR", "name": "Riel cambodgien", "symbol": "៛", "country": "KH", "flag": "🇰🇭"},
    {"code": "LAK", "name": "Kip laotien", "symbol": "₭", "country": "LA", "flag": "🇱🇦"},
    {"code": "GEL", "name": "Lari géorgien", "symbol": "₾", "country": "GE", "flag": "🇬🇪"},
    {"code": "AMD", "name": "Dram arménien", "symbol": "֏", "country": "AM", "flag": "🇦🇲"},
    {"code": "AZN", "name": "Manat azerbaïdjanais", "symbol": "₼", "country": "AZ", "flag": "🇦🇿"},
    {"code": "KZT", "name": "Tenge kazakh", "symbol": "₸", "country": "KZ", "flag": "🇰🇿"},
    {"code": "UZS", "name": "Soum ouzbek", "symbol": "soum", "country": "UZ", "flag": "🇺🇿"},
    {"code": "MNT", "name": "Tugrik mongol", "symbol": "₮", "country": "MN", "flag": "🇲🇳"},
    {"code": "AFN", "name": "Afghani", "symbol": "؋", "country": "AF", "flag": "🇦🇫"},
    {"code": "IQD", "name": "Dinar irakien", "symbol": "ع.د", "country": "IQ", "flag": "🇮🇶"},
    {"code": "IRR", "name": "Rial iranien", "symbol": "﷼", "country": "IR", "flag": "🇮🇷"},
    {"code": "SYP", "name": "Livre syrienne", "symbol": "£S", "country": "SY", "flag": "🇸🇾"},
    {"code": "YER", "name": "Rial yéménite", "symbol": "﷼", "country": "YE", "flag": "🇾🇪"},
    {"code": "MVR", "name": "Rufiyaa maldivien", "symbol": "Rf", "country": "MV", "flag": "🇲🇻"},
    {"code": "BTN", "name": "Ngultrum bhoutanais", "symbol": "Nu.", "country": "BT", "flag": "🇧🇹"},
    {"code": "BND", "name": "Dollar de Brunei", "symbol": "B$", "country": "BN", "flag": "🇧🇳"},
    {"code": "FJD", "name": "Dollar fidjien", "symbol": "FJ$", "country": "FJ", "flag": "🇫🇯"},
    {"code": "PGK", "name": "Kina", "symbol": "K", "country": "PG", "flag": "🇵🇬"},
    {"code": "WST", "name": "Tala", "symbol": "WS$", "country": "WS", "flag": "🇼🇸"},
    {"code": "TOP", "name": "Pa'anga", "symbol": "T$", "country": "TO", "flag": "🇹🇴"},
    {"code": "VUV", "name": "Vatu", "symbol": "VT", "country": "VU", "flag": "🇻🇺"},
    {"code": "XPF", "name": "Franc CFP", "symbol": "₣", "country": "NC", "flag": "🇳🇨"},
    {"code": "JMD", "name": "Dollar jamaïcain", "symbol": "J$", "country": "JM", "flag": "🇯🇲"},
    {"code": "HTG", "name": "Gourde haïtienne", "symbol": "G", "country": "HT", "flag": "🇭🇹"},
    {"code": "DOP", "name": "Peso dominicain", "symbol": "RD$", "country": "DO", "flag": "🇩🇴"},
    {"code": "CUP", "name": "Peso cubain", "symbol": "$MN", "country": "CU", "flag": "🇨🇺"},
    {"code": "TTD", "name": "Dollar de Trinité", "symbol": "TT$", "country": "TT", "flag": "🇹🇹"},
    {"code": "BBD", "name": "Dollar barbadien", "symbol": "Bds$", "country": "BB", "flag": "🇧🇧"},
    {"code": "BSD", "name": "Dollar bahaméen", "symbol": "B$", "country": "BS", "flag": "🇧🇸"},
    {"code": "PAB", "name": "Balboa panaméen", "symbol": "B/.", "country": "PA", "flag": "🇵🇦"},
    {"code": "CRC", "name": "Colon costaricain", "symbol": "₡", "country": "CR", "flag": "🇨🇷"},
    {"code": "GTQ", "name": "Quetzal guatémaltèque", "symbol": "Q", "country": "GT", "flag": "🇬🇹"},
    {"code": "HNL", "name": "Lempira hondurien", "symbol": "L", "country": "HN", "flag": "🇭🇳"},
    {"code": "NIO", "name": "Cordoba nicaraguayen", "symbol": "C$", "country": "NI", "flag": "🇳🇮"},
    {"code": "BZD", "name": "Dollar bélizien", "symbol": "BZ$", "country": "BZ", "flag": "🇧🇿"},
    {"code": "BOB", "name": "Boliviano", "symbol": "Bs", "country": "BO", "flag": "🇧🇴"},
    {"code": "VES", "name": "Bolivar vénézuélien", "symbol": "Bs.S", "country": "VE", "flag": "🇻🇪"},
    {"code": "PYG", "name": "Guarani paraguayen", "symbol": "₲", "country": "PY", "flag": "🇵🇾"},
    {"code": "UYU", "name": "Peso uruguayen", "symbol": "$U", "country": "UY", "flag": "🇺🇾"},
    {"code": "GYD", "name": "Dollar guyanien", "symbol": "GY$", "country": "GY", "flag": "🇬🇾"},
    {"code": "SRD", "name": "Dollar surinamais", "symbol": "SRD", "country": "SR", "flag": "🇸🇷"},
    {"code": "LYD", "name": "Dinar libyen", "symbol": "LD", "country": "LY", "flag": "🇱🇾"},
    {"code": "SDG", "name": "Livre soudanaise", "symbol": "ج.س", "country": "SD", "flag": "🇸🇩"},
    {"code": "SSP", "name": "Livre sud-soudanaise", "symbol": "SSP", "country": "SS", "flag": "🇸🇸"},
    {"code": "MRU", "name": "Ouguiya mauritanien", "symbol": "UM", "country": "MR", "flag": "🇲🇷"},
    {"code": "GMD", "name": "Dalasi gambien", "symbol": "D", "country": "GM", "flag": "🇬🇲"},
    {"code": "GNF", "name": "Franc guinéen", "symbol": "FG", "country": "GN", "flag": "🇬🇳"},
    {"code": "SLL", "name": "Leone sierra-léonais", "symbol": "Le", "country": "SL", "flag": "🇸🇱"},
    {"code": "LRD", "name": "Dollar libérien", "symbol": "L$", "country": "LR", "flag": "🇱🇷"},
    {"code": "CVE", "name": "Escudo cap-verdien", "symbol": "$", "country": "CV", "flag": "🇨🇻"},
    {"code": "CDF", "name": "Franc congolais", "symbol": "FC", "country": "CD", "flag": "🇨🇩"},
    {"code": "AOA", "name": "Kwanza angolais", "symbol": "Kz", "country": "AO", "flag": "🇦🇴"},
    {"code": "MZN", "name": "Metical mozambicain", "symbol": "MT", "country": "MZ", "flag": "🇲🇿"},
    {"code": "ZWL", "name": "Dollar zimbabwéen", "symbol": "Z$", "country": "ZW", "flag": "🇿🇼"},
    {"code": "ZMW", "name": "Kwacha zambien", "symbol": "ZK", "country": "ZM", "flag": "🇿🇲"},
    {"code": "MWK", "name": "Kwacha malawite", "symbol": "MK", "country": "MW", "flag": "🇲🇼"},
    {"code": "BWP", "name": "Pula botswanais", "symbol": "P", "country": "BW", "flag": "🇧🇼"},
    {"code": "NAD", "name": "Dollar namibien", "symbol": "N$", "country": "NA", "flag": "🇳🇦"},
    {"code": "SZL", "name": "Lilangeni swazi", "symbol": "E", "country": "SZ", "flag": "🇸🇿"},
    {"code": "LSL", "name": "Loti lesothan", "symbol": "L", "country": "LS", "flag": "🇱🇸"},
    {"code": "MGA", "name": "Ariary malgache", "symbol": "Ar", "country": "MG", "flag": "🇲🇬"},
    {"code": "KMF", "name": "Franc comorien", "symbol": "CF", "country": "KM", "flag": "🇰🇲"},
    {"code": "SCR", "name": "Roupie seychelloise", "symbol": "Rs", "country": "SC", "flag": "🇸🇨"},
    {"code": "DJF", "name": "Franc djiboutien", "symbol": "Fdj", "country": "DJ", "flag": "🇩🇯"},
    {"code": "ERN", "name": "Nakfa érythréen", "symbol": "Nfk", "country": "ER", "flag": "🇪🇷"},
    {"code": "SOS", "name": "Shilling somalien", "symbol": "Sh.So", "country": "SO", "flag": "🇸🇴"},
    {"code": "BIF", "name": "Franc burundais", "symbol": "FBu", "country": "BI", "flag": "🇧🇮"},
    {"code": "MDL", "name": "Leu moldave", "symbol": "L", "country": "MD", "flag": "🇲🇩"},
    {"code": "BYN", "name": "Rouble biélorusse", "symbol": "Br", "country": "BY", "flag": "🇧🇾"},
    {"code": "ALL", "name": "Lek albanais", "symbol": "L", "country": "AL", "flag": "🇦🇱"},
    {"code": "MKD", "name": "Denar macédonien", "symbol": "ден", "country": "MK", "flag": "🇲🇰"},
    {"code": "BAM", "name": "Mark convertible", "symbol": "KM", "country": "BA", "flag": "🇧🇦"},
]


def get_all_currencies():
    return CURRENCIES


def get_all_countries():
    return COUNTRIES


def get_country_by_code(code):
    if code in COUNTRIES:
        return {"code": code, **COUNTRIES[code]}
    return {"code": code, "name": code, "flag": ""}


def get_country_name(code):
    country = COUNTRIES.get(code, {})
    return country.get("name", code)


def get_country_flag(code):
    country = COUNTRIES.get(code, {})
    return country.get("flag", "")


def get_currency_by_code(code):
    for currency in CURRENCIES:
        if currency["code"] == code:
            return currency
    return {"code": code, "name": code, "symbol": code, "country": "", "flag": ""}


def get_currency_symbol(code):
    currency = get_currency_by_code(code)
    return currency.get("symbol", code)


def get_currency_choices():
    return [(c["code"], f"{c['flag']} {c['code']} - {c['name']}") for c in CURRENCIES]


def get_country_choices():
    return [(code, f"{info['flag']} {info['name']}") for code, info in sorted(COUNTRIES.items(), key=lambda x: x[1]['name'])]


def get_currencies_by_country(country_code):
    return [c for c in CURRENCIES if c["country"] == country_code]
