"""
World Countries and Cities Data
Complete list of all countries with ISO codes, flags, and major cities.
"""

WORLD_COUNTRIES = {
    "AF": {"name": "Afghanistan", "flag": "🇦🇫", "continent": "Asie", "currency": "AFN"},
    "AL": {"name": "Albanie", "flag": "🇦🇱", "continent": "Europe", "currency": "ALL"},
    "DZ": {"name": "Algérie", "flag": "🇩🇿", "continent": "Afrique", "currency": "DZD"},
    "AD": {"name": "Andorre", "flag": "🇦🇩", "continent": "Europe", "currency": "EUR"},
    "AO": {"name": "Angola", "flag": "🇦🇴", "continent": "Afrique", "currency": "AOA"},
    "AG": {"name": "Antigua-et-Barbuda", "flag": "🇦🇬", "continent": "Amérique", "currency": "XCD"},
    "AR": {"name": "Argentine", "flag": "🇦🇷", "continent": "Amérique", "currency": "ARS"},
    "AM": {"name": "Arménie", "flag": "🇦🇲", "continent": "Asie", "currency": "AMD"},
    "AU": {"name": "Australie", "flag": "🇦🇺", "continent": "Océanie", "currency": "AUD"},
    "AT": {"name": "Autriche", "flag": "🇦🇹", "continent": "Europe", "currency": "EUR"},
    "AZ": {"name": "Azerbaïdjan", "flag": "🇦🇿", "continent": "Asie", "currency": "AZN"},
    "BS": {"name": "Bahamas", "flag": "🇧🇸", "continent": "Amérique", "currency": "BSD"},
    "BH": {"name": "Bahreïn", "flag": "🇧🇭", "continent": "Asie", "currency": "BHD"},
    "BD": {"name": "Bangladesh", "flag": "🇧🇩", "continent": "Asie", "currency": "BDT"},
    "BB": {"name": "Barbade", "flag": "🇧🇧", "continent": "Amérique", "currency": "BBD"},
    "BY": {"name": "Biélorussie", "flag": "🇧🇾", "continent": "Europe", "currency": "BYN"},
    "BE": {"name": "Belgique", "flag": "🇧🇪", "continent": "Europe", "currency": "EUR"},
    "BZ": {"name": "Belize", "flag": "🇧🇿", "continent": "Amérique", "currency": "BZD"},
    "BJ": {"name": "Bénin", "flag": "🇧🇯", "continent": "Afrique", "currency": "XOF"},
    "BT": {"name": "Bhoutan", "flag": "🇧🇹", "continent": "Asie", "currency": "BTN"},
    "BO": {"name": "Bolivie", "flag": "🇧🇴", "continent": "Amérique", "currency": "BOB"},
    "BA": {"name": "Bosnie-Herzégovine", "flag": "🇧🇦", "continent": "Europe", "currency": "BAM"},
    "BW": {"name": "Botswana", "flag": "🇧🇼", "continent": "Afrique", "currency": "BWP"},
    "BR": {"name": "Brésil", "flag": "🇧🇷", "continent": "Amérique", "currency": "BRL"},
    "BN": {"name": "Brunei", "flag": "🇧🇳", "continent": "Asie", "currency": "BND"},
    "BG": {"name": "Bulgarie", "flag": "🇧🇬", "continent": "Europe", "currency": "BGN"},
    "BF": {"name": "Burkina Faso", "flag": "🇧🇫", "continent": "Afrique", "currency": "XOF"},
    "BI": {"name": "Burundi", "flag": "🇧🇮", "continent": "Afrique", "currency": "BIF"},
    "CV": {"name": "Cap-Vert", "flag": "🇨🇻", "continent": "Afrique", "currency": "CVE"},
    "KH": {"name": "Cambodge", "flag": "🇰🇭", "continent": "Asie", "currency": "KHR"},
    "CM": {"name": "Cameroun", "flag": "🇨🇲", "continent": "Afrique", "currency": "XAF"},
    "CA": {"name": "Canada", "flag": "🇨🇦", "continent": "Amérique", "currency": "CAD"},
    "CF": {"name": "Centrafrique", "flag": "🇨🇫", "continent": "Afrique", "currency": "XAF"},
    "TD": {"name": "Tchad", "flag": "🇹🇩", "continent": "Afrique", "currency": "XAF"},
    "CL": {"name": "Chili", "flag": "🇨🇱", "continent": "Amérique", "currency": "CLP"},
    "CN": {"name": "Chine", "flag": "🇨🇳", "continent": "Asie", "currency": "CNY"},
    "CO": {"name": "Colombie", "flag": "🇨🇴", "continent": "Amérique", "currency": "COP"},
    "KM": {"name": "Comores", "flag": "🇰🇲", "continent": "Afrique", "currency": "KMF"},
    "CG": {"name": "Congo", "flag": "🇨🇬", "continent": "Afrique", "currency": "XAF"},
    "CD": {"name": "RD Congo", "flag": "🇨🇩", "continent": "Afrique", "currency": "CDF"},
    "CR": {"name": "Costa Rica", "flag": "🇨🇷", "continent": "Amérique", "currency": "CRC"},
    "HR": {"name": "Croatie", "flag": "🇭🇷", "continent": "Europe", "currency": "EUR"},
    "CU": {"name": "Cuba", "flag": "🇨🇺", "continent": "Amérique", "currency": "CUP"},
    "CY": {"name": "Chypre", "flag": "🇨🇾", "continent": "Europe", "currency": "EUR"},
    "CZ": {"name": "République Tchèque", "flag": "🇨🇿", "continent": "Europe", "currency": "CZK"},
    "CI": {"name": "Côte d'Ivoire", "flag": "🇨🇮", "continent": "Afrique", "currency": "XOF"},
    "DK": {"name": "Danemark", "flag": "🇩🇰", "continent": "Europe", "currency": "DKK"},
    "DJ": {"name": "Djibouti", "flag": "🇩🇯", "continent": "Afrique", "currency": "DJF"},
    "DM": {"name": "Dominique", "flag": "🇩🇲", "continent": "Amérique", "currency": "XCD"},
    "DO": {"name": "République Dominicaine", "flag": "🇩🇴", "continent": "Amérique", "currency": "DOP"},
    "EC": {"name": "Équateur", "flag": "🇪🇨", "continent": "Amérique", "currency": "USD"},
    "EG": {"name": "Égypte", "flag": "🇪🇬", "continent": "Afrique", "currency": "EGP"},
    "SV": {"name": "Salvador", "flag": "🇸🇻", "continent": "Amérique", "currency": "USD"},
    "GQ": {"name": "Guinée Équatoriale", "flag": "🇬🇶", "continent": "Afrique", "currency": "XAF"},
    "ER": {"name": "Érythrée", "flag": "🇪🇷", "continent": "Afrique", "currency": "ERN"},
    "EE": {"name": "Estonie", "flag": "🇪🇪", "continent": "Europe", "currency": "EUR"},
    "SZ": {"name": "Eswatini", "flag": "🇸🇿", "continent": "Afrique", "currency": "SZL"},
    "ET": {"name": "Éthiopie", "flag": "🇪🇹", "continent": "Afrique", "currency": "ETB"},
    "FJ": {"name": "Fidji", "flag": "🇫🇯", "continent": "Océanie", "currency": "FJD"},
    "FI": {"name": "Finlande", "flag": "🇫🇮", "continent": "Europe", "currency": "EUR"},
    "FR": {"name": "France", "flag": "🇫🇷", "continent": "Europe", "currency": "EUR"},
    "GA": {"name": "Gabon", "flag": "🇬🇦", "continent": "Afrique", "currency": "XAF"},
    "GM": {"name": "Gambie", "flag": "🇬🇲", "continent": "Afrique", "currency": "GMD"},
    "GE": {"name": "Géorgie", "flag": "🇬🇪", "continent": "Asie", "currency": "GEL"},
    "DE": {"name": "Allemagne", "flag": "🇩🇪", "continent": "Europe", "currency": "EUR"},
    "GH": {"name": "Ghana", "flag": "🇬🇭", "continent": "Afrique", "currency": "GHS"},
    "GR": {"name": "Grèce", "flag": "🇬🇷", "continent": "Europe", "currency": "EUR"},
    "GD": {"name": "Grenade", "flag": "🇬🇩", "continent": "Amérique", "currency": "XCD"},
    "GT": {"name": "Guatemala", "flag": "🇬🇹", "continent": "Amérique", "currency": "GTQ"},
    "GN": {"name": "Guinée", "flag": "🇬🇳", "continent": "Afrique", "currency": "GNF"},
    "GW": {"name": "Guinée-Bissau", "flag": "🇬🇼", "continent": "Afrique", "currency": "XOF"},
    "GY": {"name": "Guyana", "flag": "🇬🇾", "continent": "Amérique", "currency": "GYD"},
    "HT": {"name": "Haïti", "flag": "🇭🇹", "continent": "Amérique", "currency": "HTG"},
    "HN": {"name": "Honduras", "flag": "🇭🇳", "continent": "Amérique", "currency": "HNL"},
    "HU": {"name": "Hongrie", "flag": "🇭🇺", "continent": "Europe", "currency": "HUF"},
    "IS": {"name": "Islande", "flag": "🇮🇸", "continent": "Europe", "currency": "ISK"},
    "IN": {"name": "Inde", "flag": "🇮🇳", "continent": "Asie", "currency": "INR"},
    "ID": {"name": "Indonésie", "flag": "🇮🇩", "continent": "Asie", "currency": "IDR"},
    "IR": {"name": "Iran", "flag": "🇮🇷", "continent": "Asie", "currency": "IRR"},
    "IQ": {"name": "Irak", "flag": "🇮🇶", "continent": "Asie", "currency": "IQD"},
    "IE": {"name": "Irlande", "flag": "🇮🇪", "continent": "Europe", "currency": "EUR"},
    "IL": {"name": "Israël", "flag": "🇮🇱", "continent": "Asie", "currency": "ILS"},
    "IT": {"name": "Italie", "flag": "🇮🇹", "continent": "Europe", "currency": "EUR"},
    "JM": {"name": "Jamaïque", "flag": "🇯🇲", "continent": "Amérique", "currency": "JMD"},
    "JP": {"name": "Japon", "flag": "🇯🇵", "continent": "Asie", "currency": "JPY"},
    "JO": {"name": "Jordanie", "flag": "🇯🇴", "continent": "Asie", "currency": "JOD"},
    "KZ": {"name": "Kazakhstan", "flag": "🇰🇿", "continent": "Asie", "currency": "KZT"},
    "KE": {"name": "Kenya", "flag": "🇰🇪", "continent": "Afrique", "currency": "KES"},
    "KI": {"name": "Kiribati", "flag": "🇰🇮", "continent": "Océanie", "currency": "AUD"},
    "KP": {"name": "Corée du Nord", "flag": "🇰🇵", "continent": "Asie", "currency": "KPW"},
    "KR": {"name": "Corée du Sud", "flag": "🇰🇷", "continent": "Asie", "currency": "KRW"},
    "KW": {"name": "Koweït", "flag": "🇰🇼", "continent": "Asie", "currency": "KWD"},
    "KG": {"name": "Kirghizistan", "flag": "🇰🇬", "continent": "Asie", "currency": "KGS"},
    "LA": {"name": "Laos", "flag": "🇱🇦", "continent": "Asie", "currency": "LAK"},
    "LV": {"name": "Lettonie", "flag": "🇱🇻", "continent": "Europe", "currency": "EUR"},
    "LB": {"name": "Liban", "flag": "🇱🇧", "continent": "Asie", "currency": "LBP"},
    "LS": {"name": "Lesotho", "flag": "🇱🇸", "continent": "Afrique", "currency": "LSL"},
    "LR": {"name": "Liberia", "flag": "🇱🇷", "continent": "Afrique", "currency": "LRD"},
    "LY": {"name": "Libye", "flag": "🇱🇾", "continent": "Afrique", "currency": "LYD"},
    "LI": {"name": "Liechtenstein", "flag": "🇱🇮", "continent": "Europe", "currency": "CHF"},
    "LT": {"name": "Lituanie", "flag": "🇱🇹", "continent": "Europe", "currency": "EUR"},
    "LU": {"name": "Luxembourg", "flag": "🇱🇺", "continent": "Europe", "currency": "EUR"},
    "MG": {"name": "Madagascar", "flag": "🇲🇬", "continent": "Afrique", "currency": "MGA"},
    "MW": {"name": "Malawi", "flag": "🇲🇼", "continent": "Afrique", "currency": "MWK"},
    "MY": {"name": "Malaisie", "flag": "🇲🇾", "continent": "Asie", "currency": "MYR"},
    "MV": {"name": "Maldives", "flag": "🇲🇻", "continent": "Asie", "currency": "MVR"},
    "ML": {"name": "Mali", "flag": "🇲🇱", "continent": "Afrique", "currency": "XOF"},
    "MT": {"name": "Malte", "flag": "🇲🇹", "continent": "Europe", "currency": "EUR"},
    "MH": {"name": "Îles Marshall", "flag": "🇲🇭", "continent": "Océanie", "currency": "USD"},
    "MR": {"name": "Mauritanie", "flag": "🇲🇷", "continent": "Afrique", "currency": "MRU"},
    "MU": {"name": "Maurice", "flag": "🇲🇺", "continent": "Afrique", "currency": "MUR"},
    "MX": {"name": "Mexique", "flag": "🇲🇽", "continent": "Amérique", "currency": "MXN"},
    "FM": {"name": "Micronésie", "flag": "🇫🇲", "continent": "Océanie", "currency": "USD"},
    "MD": {"name": "Moldavie", "flag": "🇲🇩", "continent": "Europe", "currency": "MDL"},
    "MC": {"name": "Monaco", "flag": "🇲🇨", "continent": "Europe", "currency": "EUR"},
    "MN": {"name": "Mongolie", "flag": "🇲🇳", "continent": "Asie", "currency": "MNT"},
    "ME": {"name": "Monténégro", "flag": "🇲🇪", "continent": "Europe", "currency": "EUR"},
    "MA": {"name": "Maroc", "flag": "🇲🇦", "continent": "Afrique", "currency": "MAD"},
    "MZ": {"name": "Mozambique", "flag": "🇲🇿", "continent": "Afrique", "currency": "MZN"},
    "MM": {"name": "Myanmar", "flag": "🇲🇲", "continent": "Asie", "currency": "MMK"},
    "NA": {"name": "Namibie", "flag": "🇳🇦", "continent": "Afrique", "currency": "NAD"},
    "NR": {"name": "Nauru", "flag": "🇳🇷", "continent": "Océanie", "currency": "AUD"},
    "NP": {"name": "Népal", "flag": "🇳🇵", "continent": "Asie", "currency": "NPR"},
    "NL": {"name": "Pays-Bas", "flag": "🇳🇱", "continent": "Europe", "currency": "EUR"},
    "NZ": {"name": "Nouvelle-Zélande", "flag": "🇳🇿", "continent": "Océanie", "currency": "NZD"},
    "NI": {"name": "Nicaragua", "flag": "🇳🇮", "continent": "Amérique", "currency": "NIO"},
    "NE": {"name": "Niger", "flag": "🇳🇪", "continent": "Afrique", "currency": "XOF"},
    "NG": {"name": "Nigéria", "flag": "🇳🇬", "continent": "Afrique", "currency": "NGN"},
    "MK": {"name": "Macédoine du Nord", "flag": "🇲🇰", "continent": "Europe", "currency": "MKD"},
    "NO": {"name": "Norvège", "flag": "🇳🇴", "continent": "Europe", "currency": "NOK"},
    "OM": {"name": "Oman", "flag": "🇴🇲", "continent": "Asie", "currency": "OMR"},
    "PK": {"name": "Pakistan", "flag": "🇵🇰", "continent": "Asie", "currency": "PKR"},
    "PW": {"name": "Palaos", "flag": "🇵🇼", "continent": "Océanie", "currency": "USD"},
    "PS": {"name": "Palestine", "flag": "🇵🇸", "continent": "Asie", "currency": "ILS"},
    "PA": {"name": "Panama", "flag": "🇵🇦", "continent": "Amérique", "currency": "PAB"},
    "PG": {"name": "Papouasie-Nouvelle-Guinée", "flag": "🇵🇬", "continent": "Océanie", "currency": "PGK"},
    "PY": {"name": "Paraguay", "flag": "🇵🇾", "continent": "Amérique", "currency": "PYG"},
    "PE": {"name": "Pérou", "flag": "🇵🇪", "continent": "Amérique", "currency": "PEN"},
    "PH": {"name": "Philippines", "flag": "🇵🇭", "continent": "Asie", "currency": "PHP"},
    "PL": {"name": "Pologne", "flag": "🇵🇱", "continent": "Europe", "currency": "PLN"},
    "PT": {"name": "Portugal", "flag": "🇵🇹", "continent": "Europe", "currency": "EUR"},
    "QA": {"name": "Qatar", "flag": "🇶🇦", "continent": "Asie", "currency": "QAR"},
    "RO": {"name": "Roumanie", "flag": "🇷🇴", "continent": "Europe", "currency": "RON"},
    "RU": {"name": "Russie", "flag": "🇷🇺", "continent": "Europe", "currency": "RUB"},
    "RW": {"name": "Rwanda", "flag": "🇷🇼", "continent": "Afrique", "currency": "RWF"},
    "KN": {"name": "Saint-Kitts-et-Nevis", "flag": "🇰🇳", "continent": "Amérique", "currency": "XCD"},
    "LC": {"name": "Sainte-Lucie", "flag": "🇱🇨", "continent": "Amérique", "currency": "XCD"},
    "VC": {"name": "Saint-Vincent-et-les-Grenadines", "flag": "🇻🇨", "continent": "Amérique", "currency": "XCD"},
    "WS": {"name": "Samoa", "flag": "🇼🇸", "continent": "Océanie", "currency": "WST"},
    "SM": {"name": "Saint-Marin", "flag": "🇸🇲", "continent": "Europe", "currency": "EUR"},
    "ST": {"name": "Sao Tomé-et-Principe", "flag": "🇸🇹", "continent": "Afrique", "currency": "STN"},
    "SA": {"name": "Arabie Saoudite", "flag": "🇸🇦", "continent": "Asie", "currency": "SAR"},
    "SN": {"name": "Sénégal", "flag": "🇸🇳", "continent": "Afrique", "currency": "XOF"},
    "RS": {"name": "Serbie", "flag": "🇷🇸", "continent": "Europe", "currency": "RSD"},
    "SC": {"name": "Seychelles", "flag": "🇸🇨", "continent": "Afrique", "currency": "SCR"},
    "SL": {"name": "Sierra Leone", "flag": "🇸🇱", "continent": "Afrique", "currency": "SLL"},
    "SG": {"name": "Singapour", "flag": "🇸🇬", "continent": "Asie", "currency": "SGD"},
    "SK": {"name": "Slovaquie", "flag": "🇸🇰", "continent": "Europe", "currency": "EUR"},
    "SI": {"name": "Slovénie", "flag": "🇸🇮", "continent": "Europe", "currency": "EUR"},
    "SB": {"name": "Îles Salomon", "flag": "🇸🇧", "continent": "Océanie", "currency": "SBD"},
    "SO": {"name": "Somalie", "flag": "🇸🇴", "continent": "Afrique", "currency": "SOS"},
    "ZA": {"name": "Afrique du Sud", "flag": "🇿🇦", "continent": "Afrique", "currency": "ZAR"},
    "SS": {"name": "Soudan du Sud", "flag": "🇸🇸", "continent": "Afrique", "currency": "SSP"},
    "ES": {"name": "Espagne", "flag": "🇪🇸", "continent": "Europe", "currency": "EUR"},
    "LK": {"name": "Sri Lanka", "flag": "🇱🇰", "continent": "Asie", "currency": "LKR"},
    "SD": {"name": "Soudan", "flag": "🇸🇩", "continent": "Afrique", "currency": "SDG"},
    "SR": {"name": "Suriname", "flag": "🇸🇷", "continent": "Amérique", "currency": "SRD"},
    "SE": {"name": "Suède", "flag": "🇸🇪", "continent": "Europe", "currency": "SEK"},
    "CH": {"name": "Suisse", "flag": "🇨🇭", "continent": "Europe", "currency": "CHF"},
    "SY": {"name": "Syrie", "flag": "🇸🇾", "continent": "Asie", "currency": "SYP"},
    "TW": {"name": "Taïwan", "flag": "🇹🇼", "continent": "Asie", "currency": "TWD"},
    "TJ": {"name": "Tadjikistan", "flag": "🇹🇯", "continent": "Asie", "currency": "TJS"},
    "TZ": {"name": "Tanzanie", "flag": "🇹🇿", "continent": "Afrique", "currency": "TZS"},
    "TH": {"name": "Thaïlande", "flag": "🇹🇭", "continent": "Asie", "currency": "THB"},
    "TL": {"name": "Timor oriental", "flag": "🇹🇱", "continent": "Asie", "currency": "USD"},
    "TG": {"name": "Togo", "flag": "🇹🇬", "continent": "Afrique", "currency": "XOF"},
    "TO": {"name": "Tonga", "flag": "🇹🇴", "continent": "Océanie", "currency": "TOP"},
    "TT": {"name": "Trinité-et-Tobago", "flag": "🇹🇹", "continent": "Amérique", "currency": "TTD"},
    "TN": {"name": "Tunisie", "flag": "🇹🇳", "continent": "Afrique", "currency": "TND"},
    "TR": {"name": "Turquie", "flag": "🇹🇷", "continent": "Asie", "currency": "TRY"},
    "TM": {"name": "Turkménistan", "flag": "🇹🇲", "continent": "Asie", "currency": "TMT"},
    "TV": {"name": "Tuvalu", "flag": "🇹🇻", "continent": "Océanie", "currency": "AUD"},
    "UG": {"name": "Ouganda", "flag": "🇺🇬", "continent": "Afrique", "currency": "UGX"},
    "UA": {"name": "Ukraine", "flag": "🇺🇦", "continent": "Europe", "currency": "UAH"},
    "AE": {"name": "Émirats Arabes Unis", "flag": "🇦🇪", "continent": "Asie", "currency": "AED"},
    "GB": {"name": "Royaume-Uni", "flag": "🇬🇧", "continent": "Europe", "currency": "GBP"},
    "US": {"name": "États-Unis", "flag": "🇺🇸", "continent": "Amérique", "currency": "USD"},
    "UY": {"name": "Uruguay", "flag": "🇺🇾", "continent": "Amérique", "currency": "UYU"},
    "UZ": {"name": "Ouzbékistan", "flag": "🇺🇿", "continent": "Asie", "currency": "UZS"},
    "VU": {"name": "Vanuatu", "flag": "🇻🇺", "continent": "Océanie", "currency": "VUV"},
    "VA": {"name": "Vatican", "flag": "🇻🇦", "continent": "Europe", "currency": "EUR"},
    "VE": {"name": "Venezuela", "flag": "🇻🇪", "continent": "Amérique", "currency": "VES"},
    "VN": {"name": "Vietnam", "flag": "🇻🇳", "continent": "Asie", "currency": "VND"},
    "YE": {"name": "Yémen", "flag": "🇾🇪", "continent": "Asie", "currency": "YER"},
    "ZM": {"name": "Zambie", "flag": "🇿🇲", "continent": "Afrique", "currency": "ZMW"},
    "ZW": {"name": "Zimbabwe", "flag": "🇿🇼", "continent": "Afrique", "currency": "ZWL"},
    "HK": {"name": "Hong Kong", "flag": "🇭🇰", "continent": "Asie", "currency": "HKD"},
    "MO": {"name": "Macao", "flag": "🇲🇴", "continent": "Asie", "currency": "MOP"},
    "XK": {"name": "Kosovo", "flag": "🇽🇰", "continent": "Europe", "currency": "EUR"},
    "RE": {"name": "La Réunion", "flag": "🇷🇪", "continent": "Afrique", "currency": "EUR"},
    "YT": {"name": "Mayotte", "flag": "🇾🇹", "continent": "Afrique", "currency": "EUR"},
    "GP": {"name": "Guadeloupe", "flag": "🇬🇵", "continent": "Amérique", "currency": "EUR"},
    "MQ": {"name": "Martinique", "flag": "🇲🇶", "continent": "Amérique", "currency": "EUR"},
    "GF": {"name": "Guyane française", "flag": "🇬🇫", "continent": "Amérique", "currency": "EUR"},
    "NC": {"name": "Nouvelle-Calédonie", "flag": "🇳🇨", "continent": "Océanie", "currency": "XPF"},
    "PF": {"name": "Polynésie française", "flag": "🇵🇫", "continent": "Océanie", "currency": "XPF"},
    "PR": {"name": "Porto Rico", "flag": "🇵🇷", "continent": "Amérique", "currency": "USD"},
    "EU": {"name": "Union Européenne", "flag": "🇪🇺", "continent": "Europe", "currency": "EUR"},
}

WORLD_CITIES = {
    "AF": ["Kaboul", "Kandahar", "Hérat", "Mazar-e-Charif", "Jalalabad", "Kunduz", "Ghazni", "Balkh", "Baghlan", "Gardez"],
    "AL": ["Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër", "Fier", "Korçë", "Berat", "Lushnjë", "Kavajë"],
    "DZ": ["Alger", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Sétif", "Djelfa", "Sidi Bel Abbès", "Biskra", "Tébessa", "El Oued", "Skikda", "Tiaret", "Béjaïa", "Tlemcen", "Ouargla", "Béchar", "Mostaganem", "Bordj Bou Arréridj"],
    "AD": ["Andorre-la-Vieille", "Escaldes-Engordany", "Encamp", "Sant Julià de Lòria", "La Massana", "Canillo", "Ordino"],
    "AO": ["Luanda", "Huambo", "Lobito", "Benguela", "Lucapa", "Kuito", "Malanje", "Namibe", "Soyo", "Cabinda"],
    "AG": ["Saint John's", "All Saints", "Liberta", "Potter's Village", "Bolans", "Swetes", "Willikies", "Freetown", "Parham", "English Harbour"],
    "AR": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan", "Resistencia", "Neuquén", "Corrientes", "Posadas", "San Luis", "Bahía Blanca", "Paraná", "Formosa", "San Salvador de Jujuy", "Río Cuarto"],
    "AM": ["Erevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan", "Abovyan", "Kapan", "Armavir", "Gavar", "Artashat"],
    "AU": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adélaïde", "Gold Coast", "Canberra", "Newcastle", "Sunshine Coast", "Wollongong", "Hobart", "Geelong", "Townsville", "Cairns", "Darwin", "Toowoomba", "Ballarat", "Bendigo", "Albury-Wodonga", "Launceston"],
    "AT": ["Vienne", "Graz", "Linz", "Salzbourg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Sankt Pölten", "Dornbirn", "Wiener Neustadt", "Steyr", "Feldkirch", "Bregenz", "Leonding", "Klosterneuburg", "Baden", "Wolfsberg", "Leoben", "Krems"],
    "AZ": ["Bakou", "Gandja", "Sumqayit", "Mingatchevir", "Lankaran", "Shaki", "Nakhitchevan", "Shirvan", "Yevlakh", "Khankendi"],
    "BS": ["Nassau", "Freeport", "West End", "Coopers Town", "Marsh Harbour", "Freetown", "High Rock", "Andros Town", "Clarence Town", "Dunmore Town"],
    "BH": ["Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali", "Isa Town", "Sitra", "Budaiya", "Jidhafs", "Sanabis"],
    "BD": ["Dacca", "Chattogram", "Khulna", "Rajshahi", "Sylhet", "Rangpur", "Comilla", "Gazipur", "Narayanganj", "Mymensingh", "Barisal", "Cox's Bazar", "Jessore", "Dinajpur", "Bogra", "Brahmanbaria", "Tangail", "Narsingdi", "Savar", "Tongi"],
    "BB": ["Bridgetown", "Speightstown", "Oistins", "Bathsheba", "Holetown", "Crane", "Warrens", "Six Roads", "Maxwell", "Prospect"],
    "BY": ["Minsk", "Homiel", "Mahiliow", "Vitebsk", "Hrodna", "Brest", "Babrouïsk", "Baranovichy", "Barysaw", "Pinsk", "Orsha", "Mazyr", "Salihorsk", "Navapolatsk", "Lida", "Maladzietchna", "Polotsk", "Jlobin", "Slonim", "Rechytsa"],
    "BE": ["Bruxelles", "Anvers", "Gand", "Charleroi", "Liège", "Bruges", "Namur", "Louvain", "Mons", "Alost", "Malines", "La Louvière", "Courtrai", "Hasselt", "Ostende", "Saint-Nicolas", "Tournai", "Genk", "Seraing", "Roulers"],
    "BZ": ["Belmopan", "Belize City", "San Ignacio", "Orange Walk", "Dangriga", "Corozal", "San Pedro", "Benque Viejo del Carmen", "Punta Gorda", "Placencia"],
    "BJ": ["Porto-Novo", "Cotonou", "Abomey-Calavi", "Djougou", "Parakou", "Bohicon", "Natitingou", "Lokossa", "Ouidah", "Abomey", "Kandi", "Savè", "Malanville", "Pobè", "Comè", "Dogbo", "Sakété", "Tchaourou", "Bassila", "Bembèrèkè"],
    "BT": ["Thimphou", "Phuntsholing", "Punakha", "Wangdue Phodrang", "Samdrup Jongkhar", "Jakar", "Trashigang", "Mongar", "Trongsa", "Paro"],
    "BO": ["La Paz", "Santa Cruz de la Sierra", "Cochabamba", "Sucre", "Oruro", "Tarija", "Potosí", "Sacaba", "Quillacollo", "Montero", "Trinidad", "Riberalta", "Yacuiba", "Warnes", "Cobija", "Villazón", "Bermejo", "Camiri", "Tupiza", "Guayaramerín"],
    "BA": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Bijeljina", "Mostar", "Prijedor", "Brčko", "Doboj", "Cazin"],
    "BW": ["Gaborone", "Francistown", "Molepolole", "Maun", "Serowe", "Selebi-Phikwe", "Kanye", "Mahalapye", "Mogoditshane", "Mochudi"],
    "BR": ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Goiânia", "Belém", "Porto Alegre", "Guarulhos", "Campinas", "São Luís", "São Gonçalo", "Maceió", "Duque de Caxias", "Campo Grande", "Natal", "Teresina", "São Bernardo do Campo", "Nova Iguaçu", "João Pessoa", "Santo André", "Osasco", "São José dos Campos", "Jaboatão dos Guararapes", "Ribeirão Preto", "Uberlândia"],
    "BN": ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar", "Jerudong", "Muara", "Sukang", "Lumut", "Panaga"],
    "BG": ["Sofia", "Plovdiv", "Varna", "Bourgas", "Roussé", "Stara Zagora", "Pleven", "Sliven", "Dobrich", "Choumen", "Pernik", "Haskovo", "Yambol", "Pazardjik", "Blagoevgrad", "Veliko Tarnovo", "Vratsa", "Gabrovo", "Vidin", "Asenovgrad"],
    "BF": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora", "Dédougou", "Kaya", "Tenkodogo", "Fada N'gourma", "Houndé", "Dori", "Réo", "Pouytenga", "Yako", "Gaoua", "Léo", "Ziniaré", "Djibo", "Kongoussi", "Nouna"],
    "BI": ["Bujumbura", "Gitega", "Muyinga", "Ruyigi", "Ngozi", "Rutana", "Bururi", "Makamba", "Kayanza", "Cibitoke"],
    "CV": ["Praia", "Mindelo", "Santa Maria", "Assomada", "Pedra Badejo", "São Filipe", "Tarrafal", "Espargos", "Porto Novo", "Calheta de São Miguel"],
    "KH": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Poipet", "Kampong Cham", "Ta Khmau", "Pursat", "Kampong Speu", "Prey Veng", "Svay Rieng", "Kampong Thom", "Koh Kong", "Kampot", "Stung Treng", "Ratanakiri", "Mondulkiri", "Kratie", "Pailin", "Kep"],
    "CM": ["Yaoundé", "Douala", "Garoua", "Bamenda", "Maroua", "Bafoussam", "Ngaoundéré", "Bertoua", "Loum", "Kumba", "Edéa", "Nkongsamba", "Buea", "Limbé", "Ebolowa", "Kribi", "Dschang", "Foumban", "Guider", "Meiganga"],
    "CA": ["Toronto", "Montréal", "Vancouver", "Calgary", "Edmonton", "Ottawa", "Winnipeg", "Québec", "Hamilton", "Kitchener", "London", "Victoria", "Halifax", "Oshawa", "Windsor", "Saskatoon", "Regina", "St. Catharines", "St. John's", "Kelowna", "Barrie", "Sherbrooke", "Guelph", "Abbotsford", "Kingston", "Trois-Rivières", "Moncton", "Chicoutimi", "Milton", "Brantford"],
    "CF": ["Bangui", "Bimbo", "Berbérati", "Carnot", "Bambari", "Bouar", "Bossangoa", "Bria", "Bangassou", "Nola"],
    "TD": ["N'Djamena", "Moundou", "Abéché", "Sarh", "Kélo", "Koumra", "Pala", "Am Timan", "Bongor", "Mongo", "Doba", "Ati", "Lai", "Oum Hadjer", "Massakory", "Moussoro", "Faya-Largeau", "Mao", "Biltine", "Fada"],
    "CL": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Arica", "Chillán", "Iquique", "Puerto Montt", "Coquimbo", "Osorno", "Valdivia", "Punta Arenas", "Copiapó", "Calama", "Los Ángeles", "Curicó"],
    "CN": ["Shanghai", "Pékin", "Canton", "Shenzhen", "Wuhan", "Chengdu", "Tianjin", "Chongqing", "Nanjing", "Xi'an", "Hangzhou", "Shenyang", "Harbin", "Suzhou", "Qingdao", "Dalian", "Zhengzhou", "Jinan", "Changsha", "Kunming", "Changchun", "Ürümqi", "Lanzhou", "Ningbo", "Fuzhou", "Hefei", "Xiamen", "Nanning", "Nanchang", "Taiyuan"],
    "CO": ["Bogota", "Medellín", "Cali", "Barranquilla", "Carthagène", "Cúcuta", "Bucaramanga", "Ibagué", "Soledad", "Soacha", "Pereira", "Santa Marta", "Villavicencio", "Bello", "Pasto", "Manizales", "Neiva", "Montería", "Valledupar", "Armenia"],
    "KM": ["Moroni", "Mutsamudu", "Fomboni", "Domoni", "Tsimbeo", "Adda-Douéni", "Sima", "Ouani", "Mirontsi", "Iconi"],
    "CG": ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Impfondo", "Ouesso", "Madingou", "Owando", "Sibiti", "Loutété"],
    "CD": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kisangani", "Kananga", "Bukavu", "Goma", "Kolwezi", "Likasi", "Tshikapa", "Kikwit", "Matadi", "Uvira", "Mbandaka", "Butembo", "Beni", "Boma", "Bunia", "Isiro", "Kindu"],
    "CR": ["San José", "Alajuela", "Cartago", "Heredia", "Liberia", "Puntarenas", "Limón", "San Francisco", "Desamparados", "Paraíso"],
    "HR": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Slavonski Brod", "Pula", "Karlovac", "Sisak", "Varaždin", "Šibenik", "Dubrovnik", "Vinkovci", "Velika Gorica", "Bjelovar", "Vukovar", "Koprivnica", "Požega", "Čakovec", "Samobor"],
    "CU": ["La Havane", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara", "Guantánamo", "Bayamo", "Las Tunas", "Cienfuegos", "Pinar del Río", "Matanzas", "Ciego de Ávila", "Sancti Spíritus", "Manzanillo", "Nuevitas", "Florida", "Cárdenas", "Morón", "Contramaestre", "Artemisa"],
    "CY": ["Nicosie", "Limassol", "Larnaca", "Paphos", "Famagouste", "Kyrenia", "Paralimni", "Morphou", "Aradippou", "Strovolos"],
    "CZ": ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "České Budějovice", "Hradec Králové", "Ústí nad Labem", "Pardubice", "Zlín", "Havířov", "Kladno", "Most", "Opava", "Karviná", "Frýdek-Místek", "Děčín", "Jihlava", "Teplice"],
    "CI": ["Abidjan", "Bouaké", "Daloa", "Yamoussoukro", "Korhogo", "San-Pédro", "Man", "Divo", "Gagnoa", "Anyama", "Abengourou", "Agboville", "Grand-Bassam", "Dabou", "Séguéla", "Duékoué", "Bondoukou", "Ferkessédougou", "Odienné", "Sinfra"],
    "DK": ["Copenhague", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle", "Roskilde", "Herning", "Hørsholm", "Helsingør", "Silkeborg", "Næstved", "Fredericia", "Viborg", "Køge", "Holstebro", "Taastrup"],
    "DJ": ["Djibouti", "Ali Sabieh", "Tadjoura", "Obock", "Dikhil", "Arta", "Yoboki", "Dorra", "Galafi", "Holhol"],
    "DM": ["Roseau", "Portsmouth", "Marigot", "Berekua", "Mahaut", "Saint Joseph", "Wesley", "Vieille Case", "La Plaine", "Castle Bruce"],
    "DO": ["Saint-Domingue", "Santiago", "Santo Domingo Este", "Santo Domingo Norte", "San Pedro de Macorís", "La Romana", "Bella Vista", "San Cristóbal", "Puerto Plata", "San Francisco de Macorís", "La Vega", "Higüey", "Moca", "Bonao", "Baní", "Azua", "Mao", "San Juan de la Maguana", "Cotuí", "Barahona"],
    "EC": ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala", "Manta", "Portoviejo", "Ambato", "Riobamba", "Quevedo", "Durán", "Ibarra", "Loja", "Milagro", "Esmeraldas", "La Libertad", "Babahoyo", "Latacunga", "Tulcán", "Otavalo"],
    "EG": ["Le Caire", "Alexandrie", "Gizeh", "Shubra El-Kheima", "Port-Saïd", "Suez", "Louxor", "Mansourah", "El-Mahalla El-Kubra", "Tanta", "Asyut", "Ismaïlia", "Fayyoum", "Zagazig", "Assouan", "Damanhur", "Minya", "Beni Suef", "Qena", "Sohag"],
    "SV": ["San Salvador", "Santa Ana", "Soyapango", "San Miguel", "Mejicanos", "Santa Tecla", "Apopa", "Delgado", "Ilopango", "San Martín"],
    "GQ": ["Malabo", "Bata", "Ebebiyín", "Aconibe", "Añisok", "Luba", "Evinayong", "Mongomo", "Mikomeseng", "Riaba"],
    "ER": ["Asmara", "Keren", "Massawa", "Assab", "Mendefera", "Dekemhare", "Adi Keyh", "Barentu", "Adi Quala", "Senafe"],
    "EE": ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Viljandi", "Maardu", "Rakvere", "Sillamäe", "Kuressaare"],
    "SZ": ["Mbabane", "Manzini", "Big Bend", "Malkerns", "Nhlangano", "Siteki", "Piggs Peak", "Simunye", "Matsapha", "Bhunya"],
    "ET": ["Addis-Abeba", "Dire Dawa", "Mekele", "Gondar", "Hawassa", "Bahir Dar", "Adama", "Jimma", "Dessie", "Jijiga", "Shashamane", "Bishoftu", "Arba Minch", "Harar", "Dila", "Nekemte", "Debre Birhan", "Asella", "Debre Markos", "Kombolcha"],
    "FJ": ["Suva", "Nausori", "Lautoka", "Nadi", "Labasa", "Ba", "Levuka", "Sigatoka", "Navua", "Rakiraki"],
    "FI": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio", "Pori", "Kouvola", "Joensuu", "Lappeenranta", "Hämeenlinna", "Vaasa", "Rovaniemi", "Seinäjoki", "Mikkeli", "Kotka", "Salo"],
    "FR": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Montpellier", "Strasbourg", "Bordeaux", "Lille", "Rennes", "Reims", "Saint-Étienne", "Le Havre", "Toulon", "Grenoble", "Dijon", "Angers", "Villeurbanne", "Nîmes", "Le Mans", "Aix-en-Provence", "Clermont-Ferrand", "Brest", "Tours", "Limoges", "Amiens", "Perpignan", "Metz", "Besançon"],
    "GA": ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda", "Mouila", "Lambaréné", "Tchibanga", "Koulamoutou", "Makokou"],
    "GM": ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni", "Lamin", "Sukuta", "Brusubi", "Gunjur", "Soma"],
    "GE": ["Tbilissi", "Batoumi", "Koutaïssi", "Roustavi", "Gori", "Soukhoumi", "Zougdidi", "Poti", "Tskhinvali", "Samtredia"],
    "DE": ["Berlin", "Hambourg", "Munich", "Cologne", "Francfort-sur-le-Main", "Stuttgart", "Düsseldorf", "Leipzig", "Dortmund", "Essen", "Brême", "Dresde", "Hanovre", "Nuremberg", "Duisbourg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster", "Mannheim", "Karlsruhe", "Augsbourg", "Wiesbaden", "Mönchengladbach", "Gelsenkirchen", "Aix-la-Chapelle", "Brunswick", "Chemnitz", "Kiel"],
    "GH": ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Ashaiman", "Sunyani", "Cape Coast", "Obuasi", "Tema", "Koforidua", "Teshie", "Ho", "Madina", "Wa", "Techiman", "Nungua", "Bolgatanga", "Berekum", "Winneba", "Ejura"],
    "GR": ["Athènes", "Thessalonique", "Patras", "Le Pirée", "Héraklion", "Larissa", "Volos", "Peristeri", "Rhodes", "Ioannina", "Kallithea", "Kalamata", "Nikaia", "Glyfada", "Acharnes", "Ilion", "Keratsini", "Chalandri", "Nea Smyrni", "Amaroussion"],
    "GD": ["Saint George's", "Gouyave", "Grenville", "Victoria", "Sauteurs", "Hillsborough", "Crochu", "La Sagesse", "Marquis", "Woburn"],
    "GT": ["Guatemala City", "Mixco", "Villa Nueva", "Petapa", "Quetzaltenango", "Escuintla", "Chinautla", "Chimaltenango", "Huehuetenango", "Cobán", "Totonicapán", "Mazatenango", "Puerto Barrios", "Antigua", "Jalapa", "Retalhuleu", "Santa Lucía Cotzumalguapa", "Zacapa", "Chiquimula", "San Marcos"],
    "GN": ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé", "Guéckédou", "Kissidougou", "Mamou", "Macenta", "Siguiri", "Faranah", "Kamsar", "Boké", "Dalaba", "Dabola", "Fria", "Coyah", "Dubréka", "Pita", "Kouroussa"],
    "GW": ["Bissau", "Bafatá", "Gabú", "Bissorã", "Bolama", "Cacheu", "Catió", "Canchungo", "Farim", "Mansôa"],
    "GY": ["Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Bartica", "Skeldon", "Rosignol", "Mahaica Village", "Mahaicony Village", "Vreed en Hoop"],
    "HT": ["Port-au-Prince", "Carrefour", "Delmas", "Cap-Haïtien", "Pétionville", "Gonaïves", "Saint-Marc", "Les Cayes", "Jacmel", "Léogâne", "Port-de-Paix", "Jérémie", "Miragoâne", "Hinche", "Fort-Liberté", "Petit-Goâve", "Ouanaminthe", "Limbé", "Kenscoff", "Croix-des-Bouquets"],
    "HN": ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso", "Villanueva", "Choluteca", "Comayagua", "Puerto Cortés", "Danlí", "Juticalpa", "Santa Rosa de Copán", "La Lima", "Tocoa", "Tela", "Siguatepeque", "Olanchito", "San Lorenzo", "Catacamas", "Yoro"],
    "HU": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs", "Győr", "Nyíregyháza", "Kecskemét", "Székesfehérvár", "Szombathely", "Szolnok", "Tatabánya", "Érd", "Kaposvár", "Veszprém", "Békéscsaba", "Zalaegerszeg", "Sopron", "Eger", "Nagykanizsa"],
    "IS": ["Reykjavik", "Kópavogur", "Hafnarfjörður", "Akureyri", "Reykjanesbær", "Garðabær", "Mosfellsbær", "Akranes", "Selfoss", "Seltjarnarnes"],
    "IN": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad", "Patna", "Vadodara", "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivli", "Vasai-Virar", "Varanasi"],
    "ID": ["Jakarta", "Surabaya", "Bandung", "Bekasi", "Medan", "Tangerang", "Depok", "Semarang", "Palembang", "Makassar", "Tangerang Selatan", "Batam", "Pekanbaru", "Bogor", "Bandar Lampung", "Padang", "Malang", "Denpasar", "Samarinda", "Tasikmalaya", "Pontianak", "Banjarmasin", "Jambi", "Balikpapan", "Surakarta", "Cimahi", "Manado", "Yogyakarta", "Kupang", "Mataram"],
    "IR": ["Téhéran", "Mashhad", "Ispahan", "Karaj", "Shiraz", "Tabriz", "Qom", "Ahvaz", "Kermanshah", "Orumiyeh", "Rasht", "Zahedan", "Hamadan", "Kerman", "Yazd", "Ardabil", "Bandar Abbas", "Arak", "Zanjan", "Sanandaj"],
    "IQ": ["Bagdad", "Bassorah", "Mossoul", "Erbil", "Kirkouk", "Souleimaniye", "Najaf", "Kerbala", "Nasiriyah", "Amarah", "Diwaniyah", "Kut", "Samarra", "Ramadi", "Baqubah", "Tikrit", "Hillah", "Fallujah", "Koufa", "Dohouk"],
    "IE": ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Swords", "Dundalk", "Bray", "Navan", "Kilkenny", "Ennis", "Carlow", "Tralee", "Newbridge", "Portlaoise", "Balbriggan", "Naas", "Mullingar", "Athlone"],
    "IL": ["Jérusalem", "Tel Aviv", "Haïfa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Beer-Sheva", "Holon", "Bnei Brak", "Ramat Gan", "Ashkelon", "Rehovot", "Bat Yam", "Beit Shemesh", "Kfar Saba", "Herzliya", "Hadera", "Modi'in", "Nazareth"],
    "IT": ["Rome", "Milan", "Naples", "Turin", "Palerme", "Gênes", "Bologne", "Florence", "Bari", "Catane", "Venise", "Vérone", "Messine", "Padoue", "Trieste", "Brescia", "Parme", "Tarente", "Prato", "Modène", "Reggio de Calabre", "Reggio d'Émilie", "Pérouse", "Ravenne", "Livourne", "Cagliari", "Foggia", "Rimini", "Salerne", "Ferrare"],
    "JM": ["Kingston", "Spanish Town", "Portmore", "Montego Bay", "May Pen", "Mandeville", "Old Harbour", "Savanna-la-Mar", "Linstead", "Half Way Tree"],
    "JP": ["Tokyo", "Yokohama", "Osaka", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kawasaki", "Kyoto", "Saitama", "Hiroshima", "Sendai", "Chiba", "Kitakyushu", "Sakai", "Niigata", "Hamamatsu", "Shizuoka", "Sagamihara", "Okayama", "Kumamoto", "Kagoshima", "Funabashi", "Hachioji", "Kawaguchi", "Setagaya", "Matsuyama", "Nishinomiya", "Utsunomiya", "Higashiosaka"],
    "JO": ["Amman", "Zarqa", "Irbid", "Russeifa", "Al-Quwaysimah", "Wadi as-Sir", "Aqaba", "Madaba", "Salt", "Mafraq"],
    "KZ": ["Almaty", "Nur-Sultan", "Chymkent", "Karaganda", "Aktobé", "Taraz", "Pavlodar", "Oust-Kamenogorsk", "Semey", "Atyrau", "Kostanay", "Petropavl", "Oral", "Kyzylorda", "Aktau", "Temirtau", "Turkestan", "Taldykorgan", "Ekibastuz", "Rudny"],
    "KE": ["Nairobi", "Mombasa", "Nakuru", "Eldoret", "Kisumu", "Thika", "Malindi", "Kitale", "Garissa", "Nyeri", "Machakos", "Meru", "Lamu", "Nanyuki", "Kakamega", "Embu", "Naivasha", "Kericho", "Bungoma", "Migori"],
    "KI": ["South Tarawa", "Betio Village", "Bikenibeu", "Teaoraereke", "Bairiki", "Eita", "Bonriki", "Buariki", "Temwaiku", "Nawerewere"],
    "KP": ["Pyongyang", "Hamhung", "Chongjin", "Nampo", "Wonsan", "Sinuiju", "Tanchon", "Kaechon", "Sariwon", "Haeju"],
    "KR": ["Séoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Goyang", "Yongin", "Seongnam", "Bucheon", "Cheongju", "Ansan", "Jeonju", "Anyang", "Hwaseong", "Cheonan", "Namyangju"],
    "KW": ["Koweït City", "Al Ahmadi", "Hawalli", "As Salimiyah", "Sabah as Salim", "Al Farwaniyah", "Al Fahahil", "Al Jahra", "Mangaf", "Ar Riqqah"],
    "KG": ["Bichkek", "Och", "Jalal-Abad", "Karakol", "Tokmok", "Özgön", "Balykchy", "Naryn", "Talas", "Kara-Balta"],
    "LA": ["Vientiane", "Paksé", "Savannakhet", "Luang Prabang", "Thakhek", "Xam Neua", "Phonsavan", "Pakxan", "Muang Xay", "Pakse"],
    "LV": ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala", "Ventspils", "Rēzekne", "Valmiera", "Jēkabpils", "Ogre"],
    "LB": ["Beyrouth", "Tripoli", "Sidon", "Tyr", "Jounieh", "Zahlé", "Baalbek", "Nabatieh", "Aley", "Batroun"],
    "LS": ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse", "Mohale's Hoek", "Quthing", "Qacha's Nek", "Butha-Buthe", "Mokhotlong", "Thaba-Tseka"],
    "LR": ["Monrovia", "Gbarnga", "Kakata", "Bensonville", "Harper", "Voinjama", "Buchanan", "Zwedru", "New Kru Town", "Harbel"],
    "LY": ["Tripoli", "Benghazi", "Misrata", "Tarhuna", "Al Khums", "Zawiya", "Ajdabiya", "Syrte", "Zintan", "Sebha"],
    "LI": ["Vaduz", "Schaan", "Balzers", "Triesen", "Eschen", "Mauren", "Triesenberg", "Ruggell", "Gamprin", "Schellenberg"],
    "LT": ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Alytus", "Marijampolė", "Mažeikiai", "Jonava", "Utena"],
    "LU": ["Luxembourg", "Esch-sur-Alzette", "Differdange", "Dudelange", "Pétange", "Ettelbruck", "Diekirch", "Strassen", "Bertrange", "Belvaux"],
    "MG": ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga", "Toliara", "Antsiranana", "Ambovombe", "Ambatondrazaka", "Morondava", "Antalaha", "Nosy Be", "Sambava", "Fort Dauphin", "Manakara", "Farafangana", "Moramanga", "Andramasina", "Tsiroanomandidy", "Mananjary"],
    "MW": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu", "Mangochi", "Karonga", "Salima", "Nkhotakota", "Liwonde"],
    "MY": ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Shah Alam", "Petaling Jaya", "Kuching", "Kota Kinabalu", "Malacca City", "Alor Setar", "Kuantan", "Subang Jaya", "Iskandar Puteri", "Seremban", "Kuala Terengganu", "Ampang Jaya", "Kota Bharu", "Sandakan", "Miri", "Taiping"],
    "MV": ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Thinadhoo", "Naifaru", "Hinnavaru", "Dhidhdhoo", "Funadhoo", "Eydhafushi"],
    "ML": ["Bamako", "Sikasso", "Mopti", "Koutiala", "Ségou", "Kayes", "Gao", "Kati", "Tombouctou", "Koulikoro", "San", "Bougouni", "Nioro du Sahel", "Niono", "Bandiagara", "Kolokani", "Djenné", "Kidal", "Markala", "Yanfolila"],
    "MT": ["La Valette", "Birkirkara", "Qormi", "Mosta", "Żabbar", "St. Paul's Bay", "San Ġwann", "Żejtun", "Sliema", "Fgura"],
    "MH": ["Majuro", "Ebeye", "Jabor", "Wotje", "Mili", "Arno", "Jaluit", "Kwajalein", "Likiep", "Namu"],
    "MR": ["Nouakchott", "Nouadhibou", "Kiffa", "Kaédi", "Rosso", "Zouérate", "Atar", "Néma", "Sélibaby", "Aleg"],
    "MU": ["Port-Louis", "Vacoas-Phoenix", "Beau-Bassin Rose-Hill", "Curepipe", "Quatre Bornes", "Triolet", "Goodlands", "Centre de Flacq", "Mahébourg", "Saint-Pierre"],
    "MX": ["Mexico", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Juárez", "Zapopan", "Mérida", "San Luis Potosí", "Aguascalientes", "Hermosillo", "Chihuahua", "Saltillo", "Mexicali", "Culiacán", "Querétaro", "Acapulco", "Morelia", "Torreón", "Cancún", "Veracruz", "Tlaquepaque", "Toluca", "Durango", "Tuxtla Gutiérrez", "Villahermosa", "Reynosa", "Mazatlán", "Oaxaca"],
    "FM": ["Palikir", "Weno", "Kolonia", "Tofol", "Colonia", "Nett", "Kitti", "Madolenihm", "Sokehs", "Kapingamarangi"],
    "MD": ["Chișinău", "Tiraspol", "Bălți", "Bender", "Rîbnița", "Cahul", "Ungheni", "Soroca", "Orhei", "Dubăsari"],
    "MC": ["Monaco", "Monte-Carlo", "La Condamine", "Fontvieille", "Moneghetti", "Larvotto", "Saint-Roman", "La Colle", "Les Révoires", "Le Portier"],
    "MN": ["Oulan-Bator", "Erdenet", "Darkhan", "Choibalsan", "Mörön", "Nalaikh", "Bayankhongor", "Ölgii", "Khovd", "Sükhbaatar"],
    "ME": ["Podgorica", "Nikšić", "Pljevlja", "Bijelo Polje", "Herceg Novi", "Berane", "Cetinje", "Budva", "Bar", "Ulcinj"],
    "MA": ["Casablanca", "Rabat", "Fès", "Marrakech", "Tanger", "Salé", "Meknès", "Oujda", "Kénitra", "Agadir", "Tétouan", "Temara", "Mohammedia", "El Jadida", "Nador", "Khouribga", "Béni Mellal", "Safi", "Taza", "Laâyoune", "Settat", "Berkane", "Khemisset", "Inezgane", "Ksar El Kebir", "Larache", "Guelmim", "Berrechid", "Ouarzazate", "Fquih Ben Salah"],
    "MZ": ["Maputo", "Matola", "Nampula", "Beira", "Chimoio", "Nacala", "Quelimane", "Tete", "Lichinga", "Pemba"],
    "MM": ["Naypyidaw", "Rangoun", "Mandalay", "Mawlamyine", "Bago", "Pathein", "Monywa", "Meiktila", "Sittwe", "Mergui"],
    "NA": ["Windhoek", "Rundu", "Walvis Bay", "Oshakati", "Swakopmund", "Katima Mulilo", "Grootfontein", "Rehoboth", "Otjiwarongo", "Okahandja"],
    "NR": ["Yaren", "Denigomodu", "Meneng", "Buada", "Baiti", "Boe", "Aiwo", "Anetan", "Anabar", "Ewa"],
    "NP": ["Katmandou", "Pokhara", "Lalitpur", "Biratnagar", "Birgunj", "Bharatpur", "Janakpur", "Hetauda", "Dharan", "Butwal", "Mahendranagar", "Nepalgunj", "Bhaktapur", "Dhangadhi", "Itahari", "Ghorahi", "Tulsipur", "Rajbiraj", "Damak", "Siddharthanagar"],
    "NL": ["Amsterdam", "Rotterdam", "La Haye", "Utrecht", "Eindhoven", "Tilburg", "Groningue", "Almere", "Breda", "Nimègue", "Enschede", "Arnhem", "Haarlem", "Zaanstad", "Amersfoort", "Apeldoorn", "Bois-le-Duc", "Hoofddorp", "Maastricht", "Leyde"],
    "NZ": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Napier-Hastings", "Dunedin", "Palmerston North", "Nelson", "Rotorua", "New Plymouth", "Whangarei", "Invercargill", "Whanganui", "Gisborne", "Blenheim", "Pukekohe", "Timaru", "Masterton", "Taupo"],
    "NI": ["Managua", "León", "Masaya", "Matagalpa", "Tipitapa", "Chinandega", "Estelí", "Granada", "Jinotega", "Ciudad Sandino", "Juigalpa", "El Viejo", "Nueva Guinea", "Bluefields", "Rivas", "Chichigalpa", "Ocotal", "Jalapa", "Diriamba", "Jinotepe"],
    "NE": ["Niamey", "Zinder", "Maradi", "Tahoua", "Agadez", "Dosso", "Tessaoua", "Tillabéri", "Diffa", "Arlit", "Birni N'Konni", "Nguigmi", "Madaoua", "Maïné-Soroa", "Magaria", "Mirriah", "Tanout", "Dakoro", "Tchintabaraden", "Gouré"],
    "NG": ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Maiduguri", "Zaria", "Aba", "Jos", "Ilorin", "Oyo", "Enugu", "Abeokuta", "Kaduna", "Sokoto", "Onitsha", "Warri", "Uyo", "Calabar", "Katsina", "Akure", "Bauchi", "Ebute Ikorodu", "Makurdi", "Minna", "Umuahia", "Owerri", "Ado-Ekiti", "Yola"],
    "MK": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Ohrid", "Veles", "Štip", "Gostivar", "Strumica"],
    "NO": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad", "Kristiansand", "Sandnes", "Tromsø", "Sarpsborg", "Skien", "Ålesund", "Sandefjord", "Haugesund", "Tønsberg", "Moss", "Porsgrunn", "Bodø", "Arendal", "Hamar"],
    "OM": ["Mascate", "Seeb", "Salalah", "Bawshar", "Sohar", "As Suwayq", "Ibri", "Saham", "Barka", "Rustaq"],
    "PK": ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Gujranwala", "Peshawar", "Multan", "Hyderabad", "Islamabad", "Quetta", "Bahawalpur", "Sargodha", "Sialkot", "Sukkur", "Larkana", "Sheikhupura", "Jhang", "Rahim Yar Khan", "Mardan", "Gujrat", "Kasur", "Sahiwal", "Wah Cantonment", "Okara", "Mingora", "Nawabshah", "Chiniot", "Kotri", "Kamoke", "Hafizabad"],
    "PW": ["Ngerulmud", "Koror", "Meyuns", "Airai", "Kloulklubed", "Melekeok", "Imeong", "Ngardmau", "Ollei", "Sonsorol"],
    "PS": ["Gaza", "Hébron", "Naplouse", "Khan Younès", "Ramallah", "Jabalia", "Rafah", "Deir al-Balah", "Bethléem", "Jénine"],
    "PA": ["Panama City", "San Miguelito", "Tocumen", "David", "Arraiján", "Colón", "Las Cumbres", "La Chorrera", "Pacora", "Santiago"],
    "PG": ["Port Moresby", "Lae", "Arawa", "Mount Hagen", "Popondetta", "Madang", "Kokopo", "Mendi", "Kimbe", "Goroka"],
    "PY": ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Capiatá", "Lambaré", "Fernando de la Mora", "Limpio", "Ñemby", "Encarnación", "Mariano Roque Alonso", "Pedro Juan Caballero", "Villa Elisa", "Caaguazú", "Itauguá", "Coronel Oviedo", "Presidente Franco", "Concepción", "Villarrica", "Pilar"],
    "PE": ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura", "Iquitos", "Cusco", "Huancayo", "Chimbote", "Pucallpa", "Tacna", "Juliaca", "Ica", "Sullana", "Ayacucho", "Chincha Alta", "Cajamarca", "Huánuco", "Tarapoto", "Puno"],
    "PH": ["Quezon City", "Manille", "Davao", "Caloocan", "Cebu", "Zamboanga", "Taguig", "Antipolo", "Pasig", "Cagayan de Oro", "Parañaque", "Valenzuela", "Dasmariñas", "Las Piñas", "Makati", "General Santos", "Bacoor", "Muntinlupa", "San Jose del Monte", "Bacolod"],
    "PL": ["Varsovie", "Cracovie", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Katowice", "Białystok", "Gdynia", "Częstochowa", "Radom", "Sosnowiec", "Toruń", "Kielce", "Rzeszów", "Gliwice", "Zabrze", "Olsztyn", "Bielsko-Biała", "Bytom", "Zielona Góra", "Rybnik", "Ruda Śląska", "Tychy", "Opole", "Gorzów Wielkopolski", "Dąbrowa Górnicza"],
    "PT": ["Lisbonne", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Almada", "Coimbra", "Funchal", "Setúbal", "Agualva-Cacém", "Queluz", "Aveiro", "Viseu", "Guimarães", "Odivelas", "Leiria", "Évora", "Póvoa de Varzim", "Vila Franca de Xira", "Faro"],
    "QA": ["Doha", "Al Rayyan", "Umm Salal", "Al Wakrah", "Al Khor", "Dukhan", "Mesaieed", "Al Wukair", "Lusail", "Al Daayen"],
    "RO": ["Bucarest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Brașov", "Galați", "Ploiești", "Oradea", "Brăila", "Arad", "Pitești", "Sibiu", "Bacău", "Târgu Mureș", "Baia Mare", "Buzău", "Botoșani", "Satu Mare"],
    "RU": ["Moscou", "Saint-Pétersbourg", "Novossibirsk", "Iekaterinbourg", "Nijni Novgorod", "Kazan", "Tcheliabinsk", "Omsk", "Samara", "Rostov-sur-le-Don", "Oufa", "Krasnoïarsk", "Perm", "Voronej", "Volgograd", "Krasnodar", "Saratov", "Tioumen", "Togliatti", "Ijevsk", "Barnaoul", "Oulianovsk", "Irkoutsk", "Khabarovsk", "Vladivostok", "Iaroslavl", "Makhatchkala", "Tomsk", "Orenbourg", "Kemerovo"],
    "RW": ["Kigali", "Butare", "Gitarama", "Ruhengeri", "Gisenyi", "Byumba", "Cyangugu", "Nyanza", "Kabuga", "Rwamagana"],
    "KN": ["Basseterre", "Sandy Point Town", "Dieppe Bay Town", "Charlestown", "Gingerland", "Newcastle", "Figtree", "Tabernacle", "Old Road Town", "Cayon"],
    "LC": ["Castries", "Vieux Fort", "Micoud", "Soufrière", "Dennery", "Gros Islet", "Laborie", "Canaries", "Choiseul", "Anse La Raye"],
    "VC": ["Kingstown", "Georgetown", "Byera Village", "Biabou", "Barrouallie", "Chateaubelair", "Layou", "Port Elizabeth", "Calliaqua", "Clare Valley"],
    "WS": ["Apia", "Vaitele", "Faleula", "Siusega", "Afega", "Leulumoega", "Malie", "Solosolo", "Moamoa", "Saleimoa"],
    "SM": ["Saint-Marin", "Serravalle", "Borgo Maggiore", "Domagnano", "Fiorentino", "Acquaviva", "Faetano", "Montegiardino", "Chiesanuova", "Poggio di Chiesanuova"],
    "ST": ["São Tomé", "Santo Amaro", "Neves", "Santana", "Trindade", "Santa Catarina", "Guadalupe", "Pantufo", "São João dos Angolares", "Porto Alegre"],
    "SA": ["Riyad", "Djeddah", "La Mecque", "Médine", "Dammam", "Taïf", "Tabuk", "Khobar", "Buraidah", "Khamis Mushait", "Hafr Al-Batin", "Hail", "Najran", "Jubail", "Yanbu", "Abha", "Al Ahsa", "Jizan", "Sakaka", "Arar"],
    "SN": ["Dakar", "Pikine", "Touba", "Thiès", "Rufisque", "Kaolack", "M'Bour", "Saint-Louis", "Ziguinchor", "Diourbel", "Louga", "Tambacounda", "Richard-Toll", "Kolda", "Mbacké", "Tivaouane", "Joal-Fadiouth", "Dagana", "Sédhiou", "Linguère"],
    "RS": ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin", "Pančevo", "Čačak", "Novi Pazar", "Kraljevo", "Smederevo", "Leskovac", "Užice", "Vranje", "Valjevo", "Šabac", "Kruševac", "Sombor", "Požarevac", "Pirot"],
    "SC": ["Victoria", "Anse Boileau", "Bel Ombre", "Beau Vallon", "Cascade", "Takamaka", "Port Glaud", "Au Cap", "La Digue", "Grand Anse"],
    "SL": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu", "Lunsar", "Port Loko", "Waterloo", "Kabala", "Magburaka"],
    "SG": ["Singapour", "Woodlands", "Jurong West", "Tampines", "Hougang", "Bedok", "Ang Mo Kio", "Bukit Batok", "Clementi", "Pasir Ris"],
    "SK": ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra", "Banská Bystrica", "Trnava", "Martin", "Trenčín", "Poprad"],
    "SI": ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo Mesto", "Ptuj", "Trbovlje", "Kamnik"],
    "SB": ["Honiara", "Gizo", "Auki", "Tulagi", "Buala", "Lata", "Kirakira", "Taro", "Tigoa", "Munda"],
    "SO": ["Mogadiscio", "Hargeisa", "Berbera", "Kismayo", "Merca", "Bosaso", "Baidoa", "Burao", "Beletweyne", "Gaalkacyo"],
    "ZA": ["Johannesbourg", "Le Cap", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London", "Nelspruit", "Kimberley", "Polokwane", "Pietermaritzburg", "Rustenburg", "George", "Soweto", "Midrand", "Centurion", "Alberton", "Springs", "Benoni", "Boksburg"],
    "SS": ["Juba", "Wau", "Malakal", "Yei", "Aweil", "Bor", "Rumbek", "Kuajok", "Torit", "Nimule"],
    "ES": ["Madrid", "Barcelone", "Valence", "Séville", "Saragosse", "Malaga", "Murcie", "Palma de Majorque", "Las Palmas", "Bilbao", "Alicante", "Cordoue", "Valladolid", "Vigo", "Gijón", "L'Hospitalet de Llobregat", "La Corogne", "Grenade", "Vitoria-Gasteiz", "Elche", "Oviedo", "Santa Cruz de Tenerife", "Badalona", "Carthagène", "Terrassa", "Jerez de la Frontera", "Sabadell", "Móstoles", "Alcalá de Henares", "Pampelune"],
    "LK": ["Colombo", "Sri Jayawardenepura Kotte", "Dehiwala-Mount Lavinia", "Moratuwa", "Jaffna", "Negombo", "Pita Kotte", "Kandy", "Kalmunai", "Vavuniya", "Galle", "Trincomalee", "Batticaloa", "Matara", "Ratnapura", "Anuradhapura", "Kurunegala", "Badulla", "Nuwara Eliya", "Hambantota"],
    "SD": ["Khartoum", "Omdurman", "Bahri", "Nyala", "Port-Soudan", "Kassala", "El-Obeid", "Wad Medani", "Gedaref", "El Fasher"],
    "SR": ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo", "Nieuw Amsterdam", "Mariënburg", "Wageningen", "Albina", "Groningen", "Brownsweg"],
    "SE": ["Stockholm", "Göteborg", "Malmö", "Uppsala", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping", "Lund", "Umeå", "Gävle", "Borås", "Södertälje", "Eskilstuna", "Halmstad", "Växjö", "Karlstad", "Sundsvall"],
    "CH": ["Zurich", "Genève", "Bâle", "Lausanne", "Berne", "Winterthour", "Lucerne", "Saint-Gall", "Lugano", "Bienne", "Thoune", "Köniz", "La Chaux-de-Fonds", "Fribourg", "Schaffhouse", "Coire", "Vernier", "Neuchâtel", "Uster", "Sion"],
    "SY": ["Damas", "Alep", "Homs", "Hama", "Lattaquié", "Deir ez-Zor", "Raqqa", "Idlib", "Tartous", "Hassaké", "Daraa", "Qamishli", "Douma", "Salamiyé", "Manbij", "Afrin", "Jableh", "Ariha", "Azaz", "Al-Bab"],
    "TW": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Taoyuan", "Hsinchu", "Keelung", "Chiayi", "Changhua", "Pingtung"],
    "TJ": ["Douchanbé", "Khoudjand", "Bokhtar", "Kulyab", "Istaravshan", "Vahdat", "Kofarnihon", "Tursunzoda", "Isfara", "Panjakent"],
    "TZ": ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Mbeya", "Morogoro", "Zanzibar", "Tanga", "Kigoma", "Moshi", "Tabora", "Iringa", "Songea", "Musoma", "Shinyanga", "Bukoba", "Sumbawanga", "Lindi", "Mtwara", "Njombe"],
    "TH": ["Bangkok", "Nonthaburi", "Nakhon Ratchasima", "Chiang Mai", "Hat Yai", "Udon Thani", "Pak Kret", "Khon Kaen", "Chaophraya Surasak", "Surat Thani", "Pattaya", "Nakhon Si Thammarat", "Ubon Ratchathani", "Chiang Rai", "Nakhon Pathom", "Phuket", "Phitsanulok", "Songkhla", "Rayong", "Sakon Nakhon"],
    "TL": ["Dili", "Baucau", "Maliana", "Suai", "Lospalos", "Liquiçá", "Aileu", "Manatuto", "Ainaro", "Same"],
    "TG": ["Lomé", "Sokodé", "Kara", "Kpalimé", "Atakpamé", "Bassar", "Tsévié", "Aného", "Mango", "Dapaong", "Tabligbo", "Vogan", "Notsé", "Bafilo", "Tchamba", "Badou", "Niamtougou", "Kandé", "Sotouboua", "Pagouda"],
    "TO": ["Nuku'alofa", "Neiafu", "Haveluloto", "Vaini", "Pangai", "Ohonua", "Mu'a", "Tatakamotonga", "Kolonga", "Hihifo"],
    "TT": ["Port-d'Espagne", "Chaguanas", "San Fernando", "Mon Repos", "Arima", "Point Fortin", "Marabella", "Tunapuna", "Sangre Grande", "Scarborough"],
    "TN": ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès", "Ariana", "Gafsa", "El Mourouj", "Kasserine", "La Marsa", "Ben Arous", "Monastir", "Médenine", "Tataouine", "Nabeul", "Béja", "Mahdia", "Tozeur", "Hammamet"],
    "TR": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Konya", "Gaziantep", "Mersin", "Diyarbakır", "Kayseri", "Eskişehir", "Samsun", "Denizli", "Şanlıurfa", "Adapazarı", "Malatya", "Kahramanmaraş", "Van", "Batman", "Trabzon", "Elazığ", "Erzurum", "Sivas", "Manisa", "Gebze", "Balıkesir", "Kırıkkale", "Tarsus", "Kütahya"],
    "TM": ["Achgabat", "Türkmenabat", "Daşoguz", "Mary", "Balkanabat", "Bayramaly", "Türkmenbaşy", "Tejen", "Serdar", "Ýolöten"],
    "TV": ["Funafuti", "Savave", "Tanrake", "Alapi", "Fangaua", "Kulia", "Asau", "Motufoua", "Teone", "Lofeagai"],
    "UG": ["Kampala", "Nansana", "Kira", "Mbarara", "Mukono", "Gulu", "Lugazi", "Masaka", "Kasese", "Hoima", "Lira", "Mityana", "Mubende", "Masindi", "Entebbe", "Njeru", "Kitgum", "Jinja", "Arua", "Mbale"],
    "UA": ["Kiev", "Kharkiv", "Odessa", "Dnipro", "Donetsk", "Zaporijjia", "Lviv", "Kryvyï Rih", "Mykolaïv", "Marioupol", "Louhansk", "Vinnytsia", "Simferopol", "Makiïvka", "Kherson", "Poltava", "Tchernihiv", "Tcherkassy", "Soumy", "Jytomyr", "Rivne", "Tchernivtsi", "Ternopil", "Ivano-Frankivsk", "Kropyvnytskyï", "Khmelnytsky", "Loutsk", "Bila Tserkva", "Kamianets-Podilskyï", "Oujhorod"],
    "AE": ["Dubaï", "Abou Dabi", "Charjah", "Al Ain", "Ajman", "Ras el-Khaïmah", "Fujaïrah", "Umm al-Qaïwaïn", "Khor Fakkan", "Dibba Al-Fujairah"],
    "GB": ["Londres", "Birmingham", "Leeds", "Glasgow", "Sheffield", "Bradford", "Manchester", "Liverpool", "Édimbourg", "Bristol", "Leicester", "Coventry", "Kingston upon Hull", "Cardiff", "Belfast", "Stoke-on-Trent", "Wolverhampton", "Nottingham", "Plymouth", "Southampton", "Reading", "Derby", "Northampton", "Portsmouth", "Luton", "Preston", "Aberdeen", "Milton Keynes", "Sunderland", "Norwich"],
    "US": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphie", "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "Indianapolis", "San Francisco", "Seattle", "Denver", "Washington", "Boston", "Nashville", "El Paso", "Detroit", "Portland", "Memphis", "Oklahoma City", "Las Vegas", "Louisville", "Baltimore"],
    "UY": ["Montevideo", "Salto", "Paysandú", "Las Piedras", "Rivera", "Maldonado", "Tacuarembó", "Melo", "Mercedes", "Artigas"],
    "UZ": ["Tachkent", "Samarcande", "Namangan", "Andijan", "Noukouss", "Boukhara", "Karchi", "Ferghana", "Kokand", "Margilon", "Djizak", "Ourguentch", "Termez", "Navoï", "Angren", "Almalyk", "Chirchiq", "Khiva", "Chakhrisabz", "Zarafshan"],
    "VU": ["Port-Vila", "Luganville", "Isangel", "Sola", "Lakatoro", "Saratamata", "Port Olry", "Norsup", "Longana", "Lenakel"],
    "VA": ["Vatican", "Cité du Vatican"],
    "VE": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "Barcelona", "Maturín", "Petare", "Turmero", "Ciudad Bolívar", "Barinas", "Mérida", "Cumaná", "Cabimas", "Los Teques", "Puerto la Cruz", "Punto Fijo", "Guarenas", "San Cristóbal"],
    "VN": ["Hô Chi Minh-Ville", "Hanoï", "Haiphong", "Da Nang", "Cần Thơ", "Biên Hòa", "Nha Trang", "Huế", "Vũng Tàu", "Đà Lạt", "Buôn Ma Thuột", "Quy Nhơn", "Vinh", "Hạ Long", "Long Xuyên", "Thái Nguyên", "Thanh Hóa", "Nam Định", "Rạch Giá", "Phan Thiết"],
    "YE": ["Sanaa", "Aden", "Taiz", "Al Hudaydah", "Al Mukalla", "Ibb", "Dhamar", "Amran", "Sayyan", "Zinjibar"],
    "ZM": ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Mufulira", "Livingstone", "Luanshya", "Kasama", "Chipata"],
    "ZW": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Epworth", "Gweru", "Kwekwe", "Kadoma", "Masvingo", "Chinhoyi"],
    "HK": ["Hong Kong", "Kowloon", "Victoria", "Tsuen Wan", "Tuen Mun", "Sha Tin", "Yuen Long", "Tai Po", "Sai Kung", "Wong Tai Sin"],
    "MO": ["Macao", "Taipa", "Coloane", "Cotai", "Areia Preta", "San Kio", "Fai Chi Kei"],
    "XK": ["Pristina", "Prizren", "Mitrovica", "Ferizaj", "Peja", "Gjakova", "Gjilan", "Podujeva", "Vushtrri", "Suhareka"],
    "RE": ["Saint-Denis", "Saint-Paul", "Saint-Pierre", "Le Tampon", "Saint-André", "Saint-Louis", "Le Port", "Saint-Benoît", "Sainte-Marie", "Sainte-Suzanne"],
    "YT": ["Mamoudzou", "Koungou", "Dzaoudzi", "Dembeni", "Pamandzi", "Sada", "Bandraboua", "Ouangani", "Chirongui", "Tsingoni"],
    "GP": ["Pointe-à-Pitre", "Les Abymes", "Basse-Terre", "Le Gosier", "Sainte-Anne", "Le Moule", "Petit-Bourg", "Sainte-Rose", "Capesterre-Belle-Eau", "Morne-à-l'Eau"],
    "MQ": ["Fort-de-France", "Le Lamentin", "Le Robert", "Schoelcher", "Sainte-Marie", "Le François", "Ducos", "Saint-Joseph", "La Trinité", "Rivière-Pilote"],
    "GF": ["Cayenne", "Saint-Laurent-du-Maroni", "Matoury", "Kourou", "Rémire-Montjoly", "Macouria", "Mana", "Apatou", "Grand-Santi", "Sinnamary"],
    "NC": ["Nouméa", "Mont-Dore", "Dumbéa", "Païta", "Koné", "Bourail", "La Foa", "Pouembout", "Lifou", "Koumac"],
    "PF": ["Papeete", "Faaa", "Punaauia", "Moorea-Maiao", "Pirae", "Mahina", "Paea", "Papara", "Taravao", "Arue"],
    "PR": ["San Juan", "Bayamón", "Carolina", "Ponce", "Caguas", "Guaynabo", "Mayagüez", "Arecibo", "Toa Baja", "Fajardo"],
    "EU": ["Bruxelles", "Strasbourg", "Luxembourg", "Francfort", "La Haye", "Genève"],
}


def get_all_world_countries():
    """Return all countries sorted by name."""
    return dict(sorted(WORLD_COUNTRIES.items(), key=lambda x: x[1]['name']))


def get_world_country_by_code(code):
    """Get country info by ISO code."""
    if code in WORLD_COUNTRIES:
        return {"code": code, **WORLD_COUNTRIES[code]}
    return {"code": code, "name": code, "flag": "", "continent": "", "currency": ""}


def get_world_country_choices():
    """Return list of country choices for forms."""
    choices = []
    for code, info in sorted(WORLD_COUNTRIES.items(), key=lambda x: x[1]['name']):
        choices.append({
            'code': code,
            'name': info['name'],
            'flag': info['flag'],
            'continent': info.get('continent', ''),
            'currency': info.get('currency', '')
        })
    return choices


def get_cities_for_country(country_code):
    """Get list of cities for a country."""
    return WORLD_CITIES.get(country_code, [])


def get_all_cities():
    """Get all cities organized by country."""
    return WORLD_CITIES


def search_cities(query, country_code=None, limit=20):
    """Search cities by name prefix."""
    query = query.lower().strip()
    results = []
    
    if country_code and country_code in WORLD_CITIES:
        cities = WORLD_CITIES[country_code]
        for city in cities:
            if city.lower().startswith(query):
                results.append({
                    'city': city,
                    'country_code': country_code,
                    'country_name': WORLD_COUNTRIES.get(country_code, {}).get('name', country_code)
                })
                if len(results) >= limit:
                    break
    else:
        for code, cities in WORLD_CITIES.items():
            for city in cities:
                if city.lower().startswith(query):
                    results.append({
                        'city': city,
                        'country_code': code,
                        'country_name': WORLD_COUNTRIES.get(code, {}).get('name', code)
                    })
                    if len(results) >= limit:
                        return results
    
    return results


def get_countries_by_continent(continent):
    """Get all countries for a specific continent."""
    return {
        code: info for code, info in WORLD_COUNTRIES.items() 
        if info.get('continent', '').lower() == continent.lower()
    }
